import type { TalentNode } from "../talents";

/** Arms Warrior — Phase C reference tree (~58 point budget at level 60). */
export const ARMS_TREE_V2: TalentNode[] = [
  // ── Row 0 (entry) ───────────────────────────────────────────────────────
  {
    id: "arms_war_machine",
    name: "War Machine",
    desc: "+2 ATK per rank.",
    rankDescs: ["+2 ATK.", "+4 ATK total.", "+6 ATK total."],
    maxRank: 3,
    row: 0,
    col: 2,
    requiresPoints: 0,
    scalePerRank: true,
    effect: { kind: "stat", atk: 2 },
  },

  // ── Row 1 (3 points in tree) ────────────────────────────────────────────
  {
    id: "arms_deep_wounds",
    name: "Deep Wounds",
    desc: "Bleed ticks deal +1 damage per rank.",
    rankDescs: ["Bleed +1/tick.", "Bleed +2/tick.", "Bleed +3/tick."],
    maxRank: 3,
    row: 1,
    col: 1,
    requires: "arms_war_machine",
    requiresPoints: 3,
    scalePerRank: true,
    effect: { kind: "passive", hook: "dot_amp_bleed", power: 1 },
  },
  {
    id: "arms_battle_stance",
    name: "Battle Stance",
    desc: "+3 Max HP per rank.",
    rankDescs: ["+3 Max HP.", "+6 Max HP.", "+9 Max HP."],
    maxRank: 3,
    row: 1,
    col: 3,
    requires: "arms_war_machine",
    requiresPoints: 3,
    scalePerRank: true,
    effect: { kind: "stat", maxHp: 3 },
  },

  // ── Row 2 (8 points) ────────────────────────────────────────────────────
  {
    id: "arms_overpower",
    name: "Overpower",
    desc: "+10% damage vs bleeding foes per rank.",
    rankDescs: ["+10% vs bleed.", "+20% vs bleed.", "+30% vs bleed."],
    maxRank: 3,
    row: 2,
    col: 0,
    requires: "arms_deep_wounds",
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "passive", hook: "vs_bleeding", power: 10 },
  },
  {
    id: "arms_impale",
    name: "Impale",
    desc: "Critical strikes apply bleed (power per rank).",
    rankDescs: ["Crit rend: 2 bleed.", "Crit rend: 3 bleed.", "Crit rend: 4 bleed."],
    maxRank: 3,
    row: 2,
    col: 2,
    requires: ["arms_deep_wounds", "arms_battle_stance"],
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "passive", hook: "crit_dot_bleed", power: 2 },
  },
  {
    id: "arms_veteran",
    name: "Seasoned Veteran",
    desc: "+2% crit per rank.",
    rankDescs: ["+2% crit.", "+4% crit.", "+6% crit."],
    maxRank: 3,
    row: 2,
    col: 4,
    requires: "arms_battle_stance",
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "passive", hook: "crit_bonus", power: 2 },
  },

  // ── Row 3 (15 points) ───────────────────────────────────────────────────
  {
    id: "arms_trauma",
    name: "Trauma",
    desc: "Cleave bleed lasts +1 turn per rank.",
    rankDescs: ["Cleave bleed +1t.", "Cleave bleed +2t.", "Cleave bleed +3t."],
    maxRank: 3,
    row: 3,
    col: 1,
    requires: "arms_overpower",
    requiresPoints: 15,
    scalePerRank: true,
    effect: {
      kind: "ability",
      mod: { abilityId: "cleave", statusAmp: { kind: "bleed", turnsDelta: 1 } },
    },
  },
  {
    id: "arms_mortal_wound",
    name: "Mortal Wound",
    desc: "Strike vs bleeding foes hits harder.",
    rankDescs: ["Strike +15% vs bleed.", "Strike +30% vs bleed.", "Strike +45% vs bleed."],
    maxRank: 3,
    row: 3,
    col: 3,
    requires: "arms_impale",
    requiresPoints: 15,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "strike", bonusVsBleedMult: 1.15 } },
  },

  // ── Row 4 (22 points) ───────────────────────────────────────────────────
  {
    id: "arms_bloodletting",
    name: "Bloodletting",
    desc: "Cleave hits +8% harder per rank.",
    rankDescs: ["Cleave +8%.", "Cleave +16%.", "Cleave +24%."],
    maxRank: 3,
    row: 4,
    col: 0,
    requires: "arms_trauma",
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "cleave", multDelta: 0.08 } },
  },
  {
    id: "arms_taste_for_blood",
    name: "Taste for Blood",
    desc: "Kills empower your next attack (+10% per rank).",
    rankDescs: ["Kill frenzy +10%.", "Kill frenzy +20%.", "Kill frenzy +30%."],
    maxRank: 3,
    row: 4,
    col: 2,
    requires: ["arms_trauma", "arms_mortal_wound"],
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "passive", hook: "kill_frenzy", power: 10 },
  },
  {
    id: "arms_precision",
    name: "Martial Precision",
    desc: "+3% crit per rank.",
    rankDescs: ["+3% crit.", "+6% crit.", "+9% crit."],
    maxRank: 3,
    row: 4,
    col: 4,
    requires: "arms_veteran",
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "passive", hook: "crit_bonus", power: 3 },
  },

  // ── Row 5 (30 points) ───────────────────────────────────────────────────
  {
    id: "arms_bladestorm",
    name: "Bladestorm",
    desc: "Cleave damage +10% per rank.",
    rankDescs: ["Cleave +10%.", "Cleave +20%.", "Cleave +30%."],
    maxRank: 3,
    row: 5,
    col: 1,
    requires: "arms_bloodletting",
    requiresPoints: 30,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "cleave", multDelta: 0.1 } },
  },
  {
    id: "arms_sudden_death",
    name: "Sudden Death",
    desc: "Strike +10% damage per rank.",
    rankDescs: ["Strike +10%.", "Strike +20%.", "Strike +30%."],
    maxRank: 3,
    row: 5,
    col: 3,
    requires: "arms_mortal_wound",
    requiresPoints: 30,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "strike", multDelta: 0.1 } },
  },

  // ── Row 6 (38 points) ───────────────────────────────────────────────────
  {
    id: "arms_warbreaker",
    name: "Warbreaker",
    desc: "Mortal Strike +12% per rank.",
    rankDescs: ["Mortal Strike +12%.", "Mortal Strike +24%.", "Mortal Strike +36%."],
    maxRank: 3,
    row: 6,
    col: 0,
    requires: "arms_bladestorm",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "spec_arms", multDelta: 0.12 } },
  },
  {
    id: "arms_strength_of_arms",
    name: "Strength of Arms",
    desc: "+4 ATK per rank.",
    rankDescs: ["+4 ATK.", "+8 ATK.", "+12 ATK."],
    maxRank: 3,
    row: 6,
    col: 2,
    requires: ["arms_bladestorm", "arms_sudden_death"],
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "stat", atk: 4 },
  },
  {
    id: "arms_ravager",
    name: "Deadly Calm",
    desc: "+4% crit per rank.",
    rankDescs: ["+4% crit.", "+8% crit.", "+12% crit."],
    maxRank: 3,
    row: 6,
    col: 4,
    requires: "arms_precision",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "passive", hook: "crit_bonus", power: 4 },
  },
  {
    id: "arms_tactical_mastery",
    name: "Tactical Mastery",
    desc: "Pass Turn ticks all ability cooldowns by 1.",
    maxRank: 1,
    row: 5,
    col: 4,
    requires: "arms_precision",
    requiresPoints: 30,
    effect: { kind: "passive", hook: "pass_cd_tick", power: 1 },
  },

  // ── Row 7 capstones (45 points, pick one) ───────────────────────────────
  {
    id: "arms_colossus_smash",
    name: "Colossus Smash",
    desc: "★ Strike shatters armor: 1.6× ATK, pierces guard.",
    maxRank: 1,
    row: 7,
    col: 0,
    requires: "arms_warbreaker",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "arms_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "strike",
        multDelta: 0.6,
        ignoreGuard: true,
        rename: "Colossus Smash",
        descOverride: "Armor-shattering strike. 1.6× ATK, pierces guard.",
      },
    },
  },
  {
    id: "arms_sweeping_strikes",
    name: "Sweeping Strikes",
    desc: "★ Cleave becomes a whirlwind: 2.2× ATK, brutal bleed.",
    maxRank: 1,
    row: 7,
    col: 2,
    requires: "arms_strength_of_arms",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "arms_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "cleave",
        multDelta: 0.6,
        statusAmp: { kind: "bleed", powerDelta: 3 },
        rename: "Sweeping Strikes",
        descOverride: "Whirlwind cleave. 2.2× ATK, brutal bleed.",
      },
    },
  },
  {
    id: "arms_die_by_the_sword",
    name: "Die by the Sword",
    desc: "★ Shield Wall blocks 80% and heals 20% Max HP.",
    maxRank: 1,
    row: 7,
    col: 4,
    requires: "arms_tactical_mastery",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "arms_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "wall",
        reduceDelta: 0.1,
        healPctOnShield: 0.2,
        rename: "Die by the Sword",
        descOverride: "Brace 80% next hit AND heal 20% Max HP.",
      },
    },
  },
];

/** Total ranks if fully maxed: 17×3 + 3×1 = 54 (capstone pick 1 of 3). */
export const ARMS_TREE_POINT_SINK = ARMS_TREE_V2.reduce((sum, n) => sum + (n.maxRank ?? 1), 0);
