import type { TalentNode } from "../talents";

/** Assassination Rogue — WoW: Mutilate, Envenom, Rupture, poisons, Deathmark. */
export const ASSASSINATION_TREE_V2: TalentNode[] = [
  {
    id: "assn_venomous_wounds",
    name: "Venomous Wounds",
    desc: "Bleed ticks +1 damage per rank.",
    rankDescs: ["Bleed +1/t.", "Bleed +2/t.", "Bleed +3/t."],
    maxRank: 3,
    row: 0,
    col: 2,
    requiresPoints: 0,
    scalePerRank: true,
    effect: { kind: "passive", hook: "dot_amp_bleed", power: 1 },
  },
  {
    id: "assn_exsanguinate",
    name: "Exsanguinate",
    desc: "+10% damage vs bleeding foes per rank.",
    rankDescs: ["+10% vs bleed.", "+20% vs bleed.", "+30% vs bleed."],
    maxRank: 3,
    row: 1,
    col: 1,
    requires: "assn_venomous_wounds",
    requiresPoints: 3,
    scalePerRank: true,
    effect: { kind: "passive", hook: "vs_bleeding", power: 10 },
  },
  {
    id: "assn_cold_blood",
    name: "Cold Blood",
    desc: "+3% crit per rank.",
    rankDescs: ["+3% crit.", "+6% crit.", "+9% crit."],
    maxRank: 3,
    row: 1,
    col: 3,
    requires: "assn_venomous_wounds",
    requiresPoints: 3,
    scalePerRank: true,
    effect: { kind: "passive", hook: "crit_bonus", power: 3 },
  },
  {
    id: "assn_hemorrhage",
    name: "Hemorrhage",
    desc: "Slash applies Bleed — stronger per rank.",
    rankDescs: ["Bleed 3/t.", "Bleed 4/t.", "Bleed 5/t."],
    maxRank: 3,
    row: 2,
    col: 0,
    requires: "assn_exsanguinate",
    requiresPoints: 8,
    scalePerRank: true,
    effect: {
      kind: "ability",
      mod: { abilityId: "slash", extraStatus: { kind: "bleed", turns: 3, power: 3 } },
    },
  },
  {
    id: "assn_seal_fate",
    name: "Seal Fate",
    desc: "Crits apply bleed (power per rank).",
    rankDescs: ["Crit rend 2.", "Crit rend 3.", "Crit rend 4."],
    maxRank: 3,
    row: 2,
    col: 2,
    requires: ["assn_exsanguinate", "assn_cold_blood"],
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "passive", hook: "crit_dot_bleed", power: 2 },
  },
  {
    id: "assn_master_poisoner",
    name: "Master Poisoner",
    desc: "Burn (poison) ticks +1 per rank.",
    rankDescs: ["Poison +1/t.", "Poison +2/t.", "Poison +3/t."],
    maxRank: 3,
    row: 2,
    col: 4,
    requires: "assn_cold_blood",
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "passive", hook: "dot_amp_burn", power: 1 },
  },
  {
    id: "assn_rupture_mastery",
    name: "Rupture",
    desc: "Signature Rupture bleed +1 power and +1 turn per rank.",
    rankDescs: ["Rupture +1/t +1t.", "+2/t +2t.", "+3/t +3t."],
    maxRank: 3,
    row: 3,
    col: 1,
    requires: "assn_hemorrhage",
    requiresPoints: 15,
    scalePerRank: true,
    effect: {
      kind: "ability",
      mod: { abilityId: "spec_assn", statusAmp: { kind: "bleed", powerDelta: 1, turnsDelta: 1 } },
    },
  },
  {
    id: "assn_vendetta",
    name: "Vendetta",
    desc: "Backstab +12% vs bleeding per rank.",
    rankDescs: ["Backstab +12% vs bleed.", "+24%.", "+36%."],
    maxRank: 3,
    row: 3,
    col: 3,
    requires: "assn_seal_fate",
    requiresPoints: 15,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "backstab", bonusVsBleedMult: 1.12 } },
  },
  {
    id: "assn_improved_garrote",
    name: "Improved Garrote",
    desc: "Eviscerate bleed +1 power per rank.",
    rankDescs: ["Eviscerate bleed +1.", "+2.", "+3."],
    maxRank: 3,
    row: 4,
    col: 0,
    requires: "assn_rupture_mastery",
    requiresPoints: 22,
    scalePerRank: true,
    effect: {
      kind: "ability",
      mod: { abilityId: "eviscerate", statusAmp: { kind: "bleed", powerDelta: 1 } },
    },
  },
  {
    id: "assn_poison_bomb",
    name: "Poison Bomb",
    desc: "Eviscerate +10% per rank.",
    rankDescs: ["Eviscerate +10%.", "+20%.", "+30%."],
    maxRank: 3,
    row: 4,
    col: 2,
    requires: ["assn_rupture_mastery", "assn_vendetta"],
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "eviscerate", multDelta: 0.1 } },
  },
  {
    id: "assn_blindside",
    name: "Blindside",
    desc: "+4% crit per rank.",
    rankDescs: ["+4% crit.", "+8% crit.", "+12% crit."],
    maxRank: 3,
    row: 4,
    col: 4,
    requires: "assn_master_poisoner",
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "passive", hook: "crit_bonus", power: 4 },
  },
  {
    id: "assn_dashing_scoundrel",
    name: "Dashing Scoundrel",
    desc: "Slash +10% per rank.",
    rankDescs: ["Slash +10%.", "+20%.", "+30%."],
    maxRank: 3,
    row: 5,
    col: 1,
    requires: "assn_improved_garrote",
    requiresPoints: 30,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "slash", multDelta: 0.1 } },
  },
  {
    id: "assn_systemic_failure",
    name: "Systemic Failure",
    desc: "+12% vs bleeding per rank.",
    rankDescs: ["+12% vs bleed.", "+24%.", "+36%."],
    maxRank: 3,
    row: 5,
    col: 3,
    requires: "assn_vendetta",
    requiresPoints: 30,
    scalePerRank: true,
    effect: { kind: "passive", hook: "vs_bleeding", power: 12 },
  },
  {
    id: "assn_lethal_dose",
    name: "Lethal Dose",
    desc: "+2 ATK per rank.",
    rankDescs: ["+2 ATK.", "+4 ATK.", "+6 ATK."],
    maxRank: 3,
    row: 6,
    col: 0,
    requires: "assn_poison_bomb",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "stat", atk: 2 },
  },
  {
    id: "assn_crimson_tempest",
    name: "Crimson Tempest",
    desc: "Eviscerate applies poison burn per rank.",
    rankDescs: ["Poison 3/t.", "Poison 4/t.", "Poison 5/t."],
    maxRank: 3,
    row: 6,
    col: 2,
    requires: "assn_dashing_scoundrel",
    requiresPoints: 38,
    scalePerRank: true,
    effect: {
      kind: "ability",
      mod: { abilityId: "eviscerate", extraStatus: { kind: "burn", turns: 3, power: 3 } },
    },
  },
  {
    id: "assn_elaborate_planning",
    name: "Elaborate Planning",
    desc: "Pass Turn ticks cooldowns.",
    maxRank: 1,
    row: 6,
    col: 4,
    requires: "assn_blindside",
    requiresPoints: 38,
    effect: { kind: "passive", hook: "pass_cd_tick", power: 1 },
  },
  {
    id: "assn_cap_mutilate",
    name: "Mutilate",
    desc: "★ Slash becomes Mutilate: 1.3× ATK, vicious bleed.",
    maxRank: 1,
    row: 7,
    col: 0,
    requires: "assn_lethal_dose",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "assn_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "slash",
        multDelta: 0.3,
        statusAmp: { kind: "bleed", powerDelta: 3, turnsDelta: 2 },
        rename: "Mutilate",
        descOverride: "Twin puncture. 1.3× ATK, crippling bleed.",
      },
    },
  },
  {
    id: "assn_cap_envenom",
    name: "Envenom",
    desc: "★ Eviscerate: 2.2× ATK toxic burst + poison.",
    maxRank: 1,
    row: 7,
    col: 2,
    requires: "assn_crimson_tempest",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "assn_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "eviscerate",
        multDelta: 0.4,
        extraStatus: { kind: "burn", turns: 4, power: 5 },
        rename: "Envenom",
        descOverride: "Toxic finisher. 2.2× ATK + poison burn.",
      },
    },
  },
  {
    id: "assn_cap_deathmark",
    name: "Deathmark",
    desc: "★ Backstab: 3.0× ATK vs bleeding targets.",
    maxRank: 1,
    row: 7,
    col: 4,
    requires: "assn_elaborate_planning",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "assn_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "backstab",
        bonusVsBleedMult: 2.0,
        multDelta: 0.3,
        rename: "Deathmark",
        descOverride: "Marked for death. 3.0× ATK (×2 vs bleeding).",
      },
    },
  },
];
