import type { TalentNode } from "../talents";

/** Balance Druid — WoW: Eclipse, Sunfire, Starsurge, Celestial Alignment, Fury of Elune. */
export const BALANCE_TREE_V2: TalentNode[] = [
  {
    id: "balance_eclipse",
    name: "Eclipse",
    desc: "Burn ticks +1 damage per rank.",
    rankDescs: ["Burn +1/t.", "Burn +2/t.", "Burn +3/t."],
    maxRank: 3,
    row: 0,
    col: 2,
    requiresPoints: 0,
    scalePerRank: true,
    effect: { kind: "passive", hook: "dot_amp_burn", power: 1 },
  },
  {
    id: "balance_shooting_stars",
    name: "Shooting Stars",
    desc: "+8% damage vs burning foes per rank.",
    rankDescs: ["+8% vs burn.", "+16% vs burn.", "+24% vs burn."],
    maxRank: 3,
    row: 1,
    col: 1,
    requires: "balance_eclipse",
    requiresPoints: 3,
    scalePerRank: true,
    effect: { kind: "passive", hook: "vs_burning", power: 8 },
  },
  {
    id: "balance_natures_grace",
    name: "Nature's Grace",
    desc: "Wrath +8% damage per rank.",
    rankDescs: ["Wrath +8%.", "Wrath +16%.", "Wrath +24%."],
    maxRank: 3,
    row: 1,
    col: 3,
    requires: "balance_eclipse",
    requiresPoints: 3,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "wrath", multDelta: 0.08 } },
  },
  {
    id: "balance_sunfire",
    name: "Sunfire",
    desc: "Moonfire burn +1 power per rank.",
    rankDescs: ["Moonfire burn +1.", "+2.", "+3."],
    maxRank: 3,
    row: 2,
    col: 0,
    requires: "balance_shooting_stars",
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "moonfire", statusAmp: { kind: "burn", powerDelta: 1 } } },
  },
  {
    id: "balance_starlord",
    name: "Starlord",
    desc: "+3% crit per rank.",
    rankDescs: ["+3% crit.", "+6% crit.", "+9% crit."],
    maxRank: 3,
    row: 2,
    col: 2,
    requires: ["balance_shooting_stars", "balance_natures_grace"],
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "passive", hook: "crit_bonus", power: 3 },
  },
  {
    id: "balance_astral_influence",
    name: "Astral Influence",
    desc: "+2 MAG per rank.",
    rankDescs: ["+2 MAG.", "+4 MAG.", "+6 MAG."],
    maxRank: 3,
    row: 2,
    col: 4,
    requires: "balance_natures_grace",
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "stat", mag: 2 },
  },
  {
    id: "balance_celestial_alignment",
    name: "Celestial Alignment",
    desc: "Moonfire +10% damage per rank.",
    rankDescs: ["Moonfire +10%.", "Moonfire +20%.", "Moonfire +30%."],
    maxRank: 3,
    row: 3,
    col: 1,
    requires: "balance_sunfire",
    requiresPoints: 15,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "moonfire", multDelta: 0.1 } },
  },
  {
    id: "balance_orbit_breaker",
    name: "Orbit Breaker",
    desc: "Crits ignite (potency per rank).",
    rankDescs: ["Crit burn 3/t.", "Crit burn 4/t.", "Crit burn 5/t."],
    maxRank: 3,
    row: 3,
    col: 3,
    requires: "balance_starlord",
    requiresPoints: 15,
    scalePerRank: true,
    effect: { kind: "passive", hook: "crit_dot_burn", power: 3 },
  },
  {
    id: "balance_stellar_flare",
    name: "Stellar Flare",
    desc: "Wrath +10% per rank.",
    rankDescs: ["Wrath +10%.", "Wrath +20%.", "Wrath +30%."],
    maxRank: 3,
    row: 4,
    col: 0,
    requires: "balance_celestial_alignment",
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "wrath", multDelta: 0.1 } },
  },
  {
    id: "balance_warrior_of_elune",
    name: "Warrior of Elune",
    desc: "Moonfire burn +1 turn per rank.",
    rankDescs: ["Moonfire burn +1t.", "+2t.", "+3t."],
    maxRank: 3,
    row: 4,
    col: 2,
    requires: ["balance_celestial_alignment", "balance_orbit_breaker"],
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "moonfire", statusAmp: { kind: "burn", turnsDelta: 1 } } },
  },
  {
    id: "balance_umbral_intensity",
    name: "Umbral Intensity",
    desc: "Kills empower next hit (+7% per rank).",
    rankDescs: ["Kill frenzy +7%.", "+14%.", "+21%."],
    maxRank: 3,
    row: 4,
    col: 4,
    requires: "balance_astral_influence",
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "passive", hook: "kill_frenzy", power: 7 },
  },
  {
    id: "balance_starsurge_prep",
    name: "Starsurge",
    desc: "Wrath +12% per rank.",
    rankDescs: ["Wrath +12%.", "Wrath +24%.", "Wrath +36%."],
    maxRank: 3,
    row: 5,
    col: 1,
    requires: "balance_warrior_of_elune",
    requiresPoints: 30,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "wrath", multDelta: 0.12 } },
  },
  {
    id: "balance_fury_of_elune_prep",
    name: "Starfall",
    desc: "Unlock Starfall — stars crash on ALL foes.",
    maxRank: 1,
    row: 5,
    col: 3,
    requires: "balance_orbit_breaker",
    requiresPoints: 30,
    effect: { kind: "grant_ability", abilityId: "starfall" },
  },
  {
    id: "balance_solstice",
    name: "Solstice",
    desc: "+4% crit per rank.",
    rankDescs: ["+4% crit.", "+8% crit.", "+12% crit."],
    maxRank: 3,
    row: 6,
    col: 0,
    requires: "balance_stellar_flare",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "passive", hook: "crit_bonus", power: 4 },
  },
  {
    id: "balance_convoke",
    name: "Convoke the Spirits",
    desc: "Pass Turn ticks cooldowns once.",
    maxRank: 1,
    row: 6,
    col: 2,
    requires: "balance_starsurge_prep",
    requiresPoints: 38,
    effect: { kind: "passive", hook: "pass_cd_tick", power: 1 },
  },
  {
    id: "balance_new_moon_prep",
    name: "New Moon",
    desc: "+3 MAG per rank.",
    rankDescs: ["+3 MAG.", "+6 MAG.", "+9 MAG."],
    maxRank: 3,
    row: 6,
    col: 4,
    requires: "balance_umbral_intensity",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "stat", mag: 3 },
  },
  {
    id: "balance_cap_starsurge",
    name: "Starsurge",
    desc: "★ Wrath: 1.8× MAG + burn.",
    maxRank: 1,
    row: 7,
    col: 0,
    requires: "balance_solstice",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "balance_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "wrath",
        multDelta: 0.8,
        extraStatus: { kind: "burn", turns: 3, power: 5 },
        rename: "Starsurge",
        descOverride: "Celestial strike. 1.8× MAG + burn.",
      },
    },
  },
  {
    id: "balance_cap_fury_of_elune",
    name: "Fury of Elune",
    desc: "★ Moonfire: 1.8× MAG, long burn.",
    maxRank: 1,
    row: 7,
    col: 2,
    requires: "balance_convoke",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "balance_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "moonfire",
        multDelta: 0.6,
        statusAmp: { kind: "burn", turnsDelta: 2, powerDelta: 3 },
        rename: "Fury of Elune",
        descOverride: "Lunar wrath. 1.8× MAG, long burn.",
      },
    },
  },
  {
    id: "balance_cap_new_moon",
    name: "New Moon",
    desc: "★ Wrath: 1.5× MAG, lunar burst.",
    maxRank: 1,
    row: 7,
    col: 4,
    requires: "balance_new_moon_prep",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "balance_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "wrath",
        multDelta: 0.5,
        rename: "New Moon",
        descOverride: "New moon wrath. 1.5× MAG.",
      },
    },
  },
];
