import type { TalentNode } from "../talents";

/** Blood DK — WoW: Marrowrend, Vampiric Blood, Death Strike, self-sustain tank. */
export const BLOOD_DK_TREE_V2: TalentNode[] = [
  {
    id: "blood_heartbreaker",
    name: "Heartbreaker",
    desc: "+4% lifesteal on all attacks per rank.",
    rankDescs: ["+4% leech.", "+8% leech.", "+12% leech."],
    maxRank: 3, row: 0, col: 2, requiresPoints: 0, scalePerRank: true,
    effect: { kind: "passive", hook: "lifesteal_boost", power: 4 },
  },
  {
    id: "blood_bone_shield",
    name: "Bone Shield",
    desc: "+4 Max HP and +1% dodge per rank.",
    rankDescs: ["+4 HP, +1% dodge.", "+8 HP, +2%.", "+12 HP, +3%."],
    maxRank: 3, row: 1, col: 1, requires: "blood_heartbreaker", requiresPoints: 3, scalePerRank: true,
    effect: { kind: "stat", maxHp: 4, dodge: 1 },
  },
  {
    id: "blood_red_thirst",
    name: "Red Thirst",
    desc: "Death Strike +10% per rank.",
    rankDescs: ["Death Strike +10%.", "+20%.", "+30%."],
    maxRank: 3, row: 1, col: 3, requires: "blood_heartbreaker", requiresPoints: 3, scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "deathstrike", multDelta: 0.1, lifestealDelta: 0.05 } },
  },
  {
    id: "blood_hemostasis",
    name: "Hemostasis",
    desc: "Blood Boil bleed +1 power per rank.",
    rankDescs: ["Boil bleed +1.", "+2.", "+3."],
    maxRank: 3, row: 2, col: 0, requires: "blood_bone_shield", requiresPoints: 8, scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "bloodboil", statusAmp: { kind: "bleed", powerDelta: 1 } } },
  },
  {
    id: "blood_vampiric_blood",
    name: "Vampiric Blood",
    desc: "Death Coil +10% and +10% leech per rank.",
    rankDescs: ["Death Coil +10%, +10% leech.", "+20%, +20%.", "+30%, +30%."],
    maxRank: 3, row: 2, col: 2, requires: ["blood_bone_shield", "blood_red_thirst"], requiresPoints: 8, scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "spec_blood_dk", multDelta: 0.1, lifestealDelta: 0.1 } },
  },
  {
    id: "blood_tightening_grasp",
    name: "Tightening Grasp",
    desc: "Frost Strike chill +1 turn per rank.",
    rankDescs: ["Chill +1t.", "+2t.", "+3t."],
    maxRank: 3, row: 2, col: 4, requires: "blood_red_thirst", requiresPoints: 8, scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "froststrike", statusAmp: { kind: "chill", turnsDelta: 1 } } },
  },
  {
    id: "blood_insatiable_blade",
    name: "Insatiable Blade",
    desc: "Blood Boil +10% per rank.",
    rankDescs: ["Blood Boil +10%.", "+20%.", "+30%."],
    maxRank: 3, row: 3, col: 1, requires: "blood_hemostasis", requiresPoints: 15, scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "bloodboil", multDelta: 0.1 } },
  },
  {
    id: "blood_consumption",
    name: "Consumption",
    desc: "+10% vs bleeding per rank.",
    rankDescs: ["+10% vs bleed.", "+20%.", "+30%."],
    maxRank: 3, row: 3, col: 3, requires: "blood_vampiric_blood", requiresPoints: 15, scalePerRank: true,
    effect: { kind: "passive", hook: "vs_bleeding", power: 10 },
  },
  {
    id: "blood_dancing_rune_weapon",
    name: "Dancing Rune Weapon",
    desc: "Blood Boil CD −1 per rank.",
    rankDescs: ["Boil CD −1.", "CD −2.", "CD −3."],
    maxRank: 3, row: 4, col: 0, requires: "blood_insatiable_blade", requiresPoints: 22, scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "bloodboil", cooldownDelta: -1 } },
  },
  {
    id: "blood_bloodworms",
    name: "Bloodworms",
    desc: "Bleed ticks +1 per rank.",
    rankDescs: ["Bleed +1/t.", "+2/t.", "+3/t."],
    maxRank: 3, row: 4, col: 2, requires: ["blood_insatiable_blade", "blood_consumption"], requiresPoints: 22, scalePerRank: true,
    effect: { kind: "passive", hook: "dot_amp_bleed", power: 1 },
  },
  {
    id: "blood_purgatory",
    name: "Purgatory",
    desc: "+3% dodge per rank.",
    rankDescs: ["+3% dodge.", "+6%.", "+9%."],
    maxRank: 3, row: 4, col: 4, requires: "blood_tightening_grasp", requiresPoints: 22, scalePerRank: true,
    effect: { kind: "passive", hook: "dodge_bonus", power: 3 },
  },
  {
    id: "blood_bonestorm",
    name: "Bonestorm",
    desc: "Frost Strike +10% per rank.",
    rankDescs: ["Frost Strike +10%.", "+20%.", "+30%."],
    maxRank: 3, row: 5, col: 1, requires: "blood_dancing_rune_weapon", requiresPoints: 30, scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "froststrike", multDelta: 0.1 } },
  },
  {
    id: "blood_everlasting_bond",
    name: "Everlasting Bond",
    desc: "Death Strike leech +5% per rank.",
    rankDescs: ["+5% DS leech.", "+10%.", "+15%."],
    maxRank: 3, row: 5, col: 3, requires: "blood_bloodworms", requiresPoints: 30, scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "deathstrike", lifestealDelta: 0.05 } },
  },
  {
    id: "blood_crimson_scourge",
    name: "Crimson Scourge",
    desc: "+2 ATK per rank.",
    rankDescs: ["+2 ATK.", "+4 ATK.", "+6 ATK."],
    maxRank: 3, row: 6, col: 0, requires: "blood_bonestorm", requiresPoints: 38, scalePerRank: true,
    effect: { kind: "stat", atk: 2 },
  },
  {
    id: "blood_rune_tap",
    name: "Rune Tap",
    desc: "Pass Turn ticks cooldowns.",
    maxRank: 1, row: 6, col: 4, requires: "blood_purgatory", requiresPoints: 38,
    effect: { kind: "passive", hook: "pass_cd_tick", power: 1 },
  },
  {
    id: "blood_cap_marrowrend",
    name: "Marrowrend",
    desc: "★ Death Strike: 1.6× ATK, 50% lifesteal.",
    maxRank: 1, row: 7, col: 0, requires: "blood_crimson_scourge", requiresPoints: 45,
    capstone: true, choiceGroup: "blood_capstone",
    effect: { kind: "ability", mod: { abilityId: "deathstrike", multDelta: 0.3, lifestealDelta: 0.2, rename: "Marrowrend", descOverride: "Bone rend. 1.6× ATK, heal half dealt." } },
  },
  {
    id: "blood_cap_blooddrinker",
    name: "Blooddrinker",
    desc: "★ Blood Boil: 2.0× ATK, brutal bleed.",
    maxRank: 1, row: 7, col: 2, requires: "blood_everlasting_bond", requiresPoints: 45,
    capstone: true, choiceGroup: "blood_capstone",
    effect: { kind: "ability", mod: { abilityId: "bloodboil", multDelta: 0.3, statusAmp: { kind: "bleed", powerDelta: 3 }, rename: "Blooddrinker", descOverride: "Blood chug. 2.0× ATK, heavy bleed." } },
  },
  {
    id: "blood_cap_ams",
    name: "Anti-Magic Shell",
    desc: "★ Frost Strike: deep chill + 25% lifesteal.",
    maxRank: 1, row: 7, col: 4, requires: "blood_rune_tap", requiresPoints: 45,
    capstone: true, choiceGroup: "blood_capstone",
    effect: { kind: "ability", mod: { abilityId: "froststrike", lifestealDelta: 0.25, statusAmp: { kind: "chill", turnsDelta: 1, powerDelta: 0.1 }, rename: "Anti-Magic Shell", descOverride: "Runic ward. Chill + 25% lifesteal." } },
  },
];
