import type { TalentNode } from "../talents";

/** Discipline Priest — WoW: Atonement, Penance, Evangelism, Power Word: Barrier, Pain Suppression. */
export const DISCIPLINE_TREE_V2: TalentNode[] = [
  {
    id: "disc_atonement",
    name: "Atonement",
    desc: "Smite heals you for +3% of damage per rank.",
    rankDescs: ["+3% lifesteal.", "+6% lifesteal.", "+9% lifesteal."],
    maxRank: 3,
    row: 0,
    col: 2,
    requiresPoints: 0,
    scalePerRank: true,
    effect: { kind: "passive", hook: "lifesteal_boost", power: 3 },
  },
  {
    id: "disc_barrier_faith",
    name: "Power Word: Barrier",
    desc: "Renew heals +1 per tick per rank.",
    rankDescs: ["Renew +1/t.", "Renew +2/t.", "Renew +3/t."],
    maxRank: 3,
    row: 1,
    col: 1,
    requires: "disc_atonement",
    requiresPoints: 3,
    scalePerRank: true,
    effect: { kind: "passive", hook: "hot_amp", power: 1 },
  },
  {
    id: "disc_twin_disciplines",
    name: "Twin Disciplines",
    desc: "Smite +7% damage per rank.",
    rankDescs: ["Smite +7%.", "Smite +14%.", "Smite +21%."],
    maxRank: 3,
    row: 1,
    col: 3,
    requires: "disc_atonement",
    requiresPoints: 3,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "smite", multDelta: 0.07 } },
  },
  {
    id: "disc_evangelism",
    name: "Evangelism",
    desc: "SW:Pain burn +1 power per rank.",
    rankDescs: ["SW:Pain burn +1.", "SW:Pain burn +2.", "SW:Pain burn +3."],
    maxRank: 3,
    row: 2,
    col: 0,
    requires: "disc_barrier_faith",
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "swp", statusAmp: { kind: "burn", powerDelta: 1 } } },
  },
  {
    id: "disc_borrowed_time",
    name: "Borrowed Time",
    desc: "Renew lasts +1 turn per rank.",
    rankDescs: ["Renew +1 turn.", "Renew +2 turns.", "Renew +3 turns."],
    maxRank: 3,
    row: 2,
    col: 2,
    requires: ["disc_barrier_faith", "disc_twin_disciplines"],
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "renew", hotTurnsDelta: 1 } },
  },
  {
    id: "disc_shield_discipline",
    name: "Shield Discipline",
    desc: "+1% dodge per rank.",
    rankDescs: ["+1% dodge.", "+2% dodge.", "+3% dodge."],
    maxRank: 3,
    row: 2,
    col: 4,
    requires: "disc_twin_disciplines",
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "passive", hook: "dodge_bonus", power: 1 },
  },
  {
    id: "disc_mindbender",
    name: "Mindbender",
    desc: "SW:Pain +10% damage per rank.",
    rankDescs: ["SW:Pain +10%.", "SW:Pain +20%.", "SW:Pain +30%."],
    maxRank: 3,
    row: 3,
    col: 1,
    requires: "disc_evangelism",
    requiresPoints: 15,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "swp", multDelta: 0.1 } },
  },
  {
    id: "disc_purge_the_wicked",
    name: "Purge the Wicked",
    desc: "+8% damage vs burning foes per rank.",
    rankDescs: ["+8% vs burn.", "+16% vs burn.", "+24% vs burn."],
    maxRank: 3,
    row: 3,
    col: 3,
    requires: "disc_borrowed_time",
    requiresPoints: 15,
    scalePerRank: true,
    effect: { kind: "passive", hook: "vs_burning", power: 8 },
  },
  {
    id: "disc_painful_punishment",
    name: "Painful Punishment",
    desc: "Smite +10% and +5% leech per rank.",
    rankDescs: ["Smite +10%, +5% leech.", "+20%, +10% leech.", "+30%, +15% leech."],
    maxRank: 3,
    row: 4,
    col: 0,
    requires: "disc_mindbender",
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "smite", multDelta: 0.1, lifestealDelta: 0.05 } },
  },
  {
    id: "disc_radiance",
    name: "Power Word: Radiance",
    desc: "Renew +1 heal/tick per rank.",
    rankDescs: ["Renew +1/t.", "Renew +2/t.", "Renew +3/t."],
    maxRank: 3,
    row: 4,
    col: 2,
    requires: ["disc_mindbender", "disc_purge_the_wicked"],
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "renew", hotPowerDelta: 1 } },
  },
  {
    id: "disc_contrition",
    name: "Contrition",
    desc: "+2 MAG per rank.",
    rankDescs: ["+2 MAG.", "+4 MAG.", "+6 MAG."],
    maxRank: 3,
    row: 4,
    col: 4,
    requires: "disc_shield_discipline",
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "stat", mag: 2 },
  },
  {
    id: "disc_schism",
    name: "Schism",
    desc: "SW:Pain burn +1 turn per rank.",
    rankDescs: ["SW:Pain burn +1t.", "+2t.", "+3t."],
    maxRank: 3,
    row: 5,
    col: 1,
    requires: "disc_radiance",
    requiresPoints: 30,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "swp", statusAmp: { kind: "burn", turnsDelta: 1 } } },
  },
  {
    id: "disc_luminous_barrier",
    name: "Luminous Barrier",
    desc: "+3 Max HP per rank.",
    rankDescs: ["+3 Max HP.", "+6 Max HP.", "+9 Max HP."],
    maxRank: 3,
    row: 5,
    col: 3,
    requires: "disc_purge_the_wicked",
    requiresPoints: 30,
    scalePerRank: true,
    effect: { kind: "stat", maxHp: 3 },
  },
  {
    id: "disc_penance_prep",
    name: "Penance",
    desc: "Smite +12% per rank.",
    rankDescs: ["Smite +12%.", "Smite +24%.", "Smite +36%."],
    maxRank: 3,
    row: 6,
    col: 0,
    requires: "disc_painful_punishment",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "smite", multDelta: 0.12 } },
  },
  {
    id: "disc_spirit_shell",
    name: "Spirit Shell",
    desc: "Pass Turn ticks cooldowns once.",
    maxRank: 1,
    row: 6,
    col: 2,
    requires: "disc_schism",
    requiresPoints: 38,
    effect: { kind: "passive", hook: "pass_cd_tick", power: 1 },
  },
  {
    id: "disc_shadow_covenant",
    name: "Shadow Covenant",
    desc: "Burn ticks +1 per rank.",
    rankDescs: ["Burn +1/t.", "Burn +2/t.", "Burn +3/t."],
    maxRank: 3,
    row: 6,
    col: 4,
    requires: "disc_contrition",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "passive", hook: "dot_amp_burn", power: 1 },
  },
  {
    id: "disc_cap_penance",
    name: "Penance",
    desc: "★ Smite: 1.5× MAG, heals 25% dealt.",
    maxRank: 1,
    row: 7,
    col: 0,
    requires: "disc_penance_prep",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "disc_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "smite",
        multDelta: 0.5,
        lifestealDelta: 0.25,
        rename: "Penance",
        descOverride: "Channeled bolts. 1.5× MAG, heal 25% dealt.",
      },
    },
  },
  {
    id: "disc_cap_barrier_renew",
    name: "Barrier Renew",
    desc: "★ Renew: +3 heal/tick, +3 turns.",
    maxRank: 1,
    row: 7,
    col: 2,
    requires: "disc_spirit_shell",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "disc_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "renew",
        hotPowerDelta: 3,
        hotTurnsDelta: 3,
        rename: "Barrier Renew",
        descOverride: "Shielded renewal. Heavy HoT for 7 turns.",
      },
    },
  },
  {
    id: "disc_cap_pain_suppression",
    name: "Pain Suppression",
    desc: "★ SW:Pain: 1.6× MAG, brutal burn.",
    maxRank: 1,
    row: 7,
    col: 4,
    requires: "disc_shadow_covenant",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "disc_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "swp",
        multDelta: 0.4,
        statusAmp: { kind: "burn", turnsDelta: 2, powerDelta: 3 },
        rename: "Pain Suppression",
        descOverride: "Agonizing word. 1.6× MAG, brutal burn.",
      },
    },
  },
];
