import type { TalentNode } from "../talents";

/** Feral Druid — WoW: Primal Fury, Rake, Rip, Ferocious Bite, Incarnation. */
export const FERAL_TREE_V2: TalentNode[] = [
  {
    id: "feral_primal_fury",
    name: "Primal Fury",
    desc: "Bleed ticks +1 damage per rank.",
    rankDescs: ["Bleed +1/t.", "Bleed +2/t.", "Bleed +3/t."],
    maxRank: 3,
    row: 0,
    col: 2,
    requiresPoints: 0,
    scalePerRank: true,
    effect: { kind: "passive", hook: "dot_amp_bleed", power: 1 },
  },
  {
    id: "feral_predators_swiftness",
    name: "Predator's Swiftness",
    desc: "+8% damage vs bleeding foes per rank.",
    rankDescs: ["+8% vs bleed.", "+16% vs bleed.", "+24% vs bleed."],
    maxRank: 3,
    row: 1,
    col: 1,
    requires: "feral_primal_fury",
    requiresPoints: 3,
    scalePerRank: true,
    effect: { kind: "passive", hook: "vs_bleeding", power: 8 },
  },
  {
    id: "feral_tigers_fury",
    name: "Tiger's Fury",
    desc: "Wrath +7% damage per rank.",
    rankDescs: ["Wrath +7%.", "Wrath +14%.", "Wrath +21%."],
    maxRank: 3,
    row: 1,
    col: 3,
    requires: "feral_primal_fury",
    requiresPoints: 3,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "wrath", multDelta: 0.07 } },
  },
  {
    id: "feral_rake",
    name: "Rake",
    desc: "Moonfire applies bleed — potency per rank.",
    rankDescs: ["Moonfire + Bleed 3/t.", "Bleed 4/t.", "Bleed 5/t."],
    maxRank: 3,
    row: 2,
    col: 0,
    requires: "feral_predators_swiftness",
    requiresPoints: 8,
    scalePerRank: true,
    effect: {
      kind: "ability",
      mod: { abilityId: "moonfire", extraStatus: { kind: "bleed", turns: 3, power: 3 } },
    },
  },
  {
    id: "feral_bloodtalons",
    name: "Bloodtalons",
    desc: "Crits apply bleed (power per rank).",
    rankDescs: ["Crit rend 2.", "Crit rend 3.", "Crit rend 4."],
    maxRank: 3,
    row: 2,
    col: 2,
    requires: ["feral_predators_swiftness", "feral_tigers_fury"],
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "passive", hook: "crit_dot_bleed", power: 2 },
  },
  {
    id: "feral_sabertooth",
    name: "Sabertooth",
    desc: "+2 ATK per rank.",
    rankDescs: ["+2 ATK.", "+4 ATK.", "+6 ATK."],
    maxRank: 3,
    row: 2,
    col: 4,
    requires: "feral_tigers_fury",
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "stat", atk: 2 },
  },
  {
    id: "feral_rip",
    name: "Rip",
    desc: "Moonfire bleed +1 power per rank.",
    rankDescs: ["Bleed +1/t.", "+2/t.", "+3/t."],
    maxRank: 3,
    row: 3,
    col: 1,
    requires: "feral_rake",
    requiresPoints: 15,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "moonfire", statusAmp: { kind: "bleed", powerDelta: 1 } } },
  },
  {
    id: "feral_survival_instincts",
    name: "Survival Instincts",
    desc: "Below 40% HP, +7% damage per rank.",
    rankDescs: ["+7% damage.", "+14% damage.", "+21% damage."],
    maxRank: 3,
    row: 3,
    col: 3,
    requires: "feral_bloodtalons",
    requiresPoints: 15,
    scalePerRank: true,
    effect: { kind: "passive", hook: "low_hp_dmg", power: 7 },
  },
  {
    id: "feral_feral_frenzy",
    name: "Feral Frenzy",
    desc: "Wrath +10% vs bleeding per rank.",
    rankDescs: ["Wrath +10% vs bleed.", "+20% vs bleed.", "+30% vs bleed."],
    maxRank: 3,
    row: 4,
    col: 0,
    requires: "feral_rip",
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "wrath", bonusVsBleedMult: 1.1 } },
  },
  {
    id: "feral_primal_wrath_prep",
    name: "Primal Wrath",
    desc: "Moonfire +10% per rank.",
    rankDescs: ["Moonfire +10%.", "+20%.", "+30%."],
    maxRank: 3,
    row: 4,
    col: 2,
    requires: ["feral_rip", "feral_survival_instincts"],
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "moonfire", multDelta: 0.1 } },
  },
  {
    id: "feral_brutal_slash",
    name: "Brutal Slash",
    desc: "+3% crit per rank.",
    rankDescs: ["+3% crit.", "+6% crit.", "+9% crit."],
    maxRank: 3,
    row: 4,
    col: 4,
    requires: "feral_sabertooth",
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "passive", hook: "crit_bonus", power: 3 },
  },
  {
    id: "feral_ferocious_bite_prep",
    name: "Ferocious Bite",
    desc: "Wrath +12% per rank.",
    rankDescs: ["Wrath +12%.", "+24%.", "+36%."],
    maxRank: 3,
    row: 5,
    col: 1,
    requires: "feral_primal_wrath_prep",
    requiresPoints: 30,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "wrath", multDelta: 0.12 } },
  },
  {
    id: "feral_lunar_inspiration",
    name: "Lunar Inspiration",
    desc: "Moonfire bleed +1 turn per rank.",
    rankDescs: ["Bleed +1 turn.", "+2 turns.", "+3 turns."],
    maxRank: 3,
    row: 5,
    col: 3,
    requires: "feral_survival_instincts",
    requiresPoints: 30,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "moonfire", statusAmp: { kind: "bleed", turnsDelta: 1 } } },
  },
  {
    id: "feral_apex_predator",
    name: "Apex Predator",
    desc: "Kills empower next hit (+8% per rank).",
    rankDescs: ["Kill frenzy +8%.", "+16%.", "+24%."],
    maxRank: 3,
    row: 6,
    col: 0,
    requires: "feral_feral_frenzy",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "passive", hook: "kill_frenzy", power: 8 },
  },
  {
    id: "feral_incarnation_prep",
    name: "Incarnation",
    desc: "Rejuvenation +1 heal/tick per rank.",
    rankDescs: ["Rejuv +1/t.", "+2/t.", "+3/t."],
    maxRank: 3,
    row: 6,
    col: 2,
    requires: "feral_ferocious_bite_prep",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "rejuv", hotPowerDelta: 1 } },
  },
  {
    id: "feral_ashamane",
    name: "Ashamane's Guidance",
    desc: "Pass Turn ticks cooldowns once.",
    maxRank: 1,
    row: 6,
    col: 4,
    requires: "feral_brutal_slash",
    requiresPoints: 38,
    effect: { kind: "passive", hook: "pass_cd_tick", power: 1 },
  },
  {
    id: "feral_cap_ferocious_bite",
    name: "Ferocious Bite",
    desc: "★ Wrath: 1.6× MAG, bonus vs bleeding.",
    maxRank: 1,
    row: 7,
    col: 0,
    requires: "feral_apex_predator",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "feral_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "wrath",
        multDelta: 0.6,
        bonusVsBleedMult: 1.5,
        rename: "Ferocious Bite",
        descOverride: "Savage bite. 1.6× MAG, bonus vs bleeding.",
      },
    },
  },
  {
    id: "feral_cap_primal_wrath",
    name: "Primal Wrath",
    desc: "★ Moonfire: 1.6× MAG, savage bleed.",
    maxRank: 1,
    row: 7,
    col: 2,
    requires: "feral_incarnation_prep",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "feral_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "moonfire",
        multDelta: 0.4,
        statusAmp: { kind: "bleed", powerDelta: 4, turnsDelta: 2 },
        rename: "Primal Wrath",
        descOverride: "Primal rake. 1.6× MAG, savage bleed.",
      },
    },
  },
  {
    id: "feral_cap_incarnation",
    name: "Incarnation",
    desc: "★ Rejuvenation: +4 heal/t, 7 turns.",
    maxRank: 1,
    row: 7,
    col: 4,
    requires: "feral_ashamane",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "feral_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "rejuv",
        hotPowerDelta: 4,
        hotTurnsDelta: 3,
        rename: "Incarnation",
        descOverride: "Predator's renewal. +4 heal/t, 7 turns.",
      },
    },
  },
];
