import type { TalentNode } from "../talents";

/** Frost DK — WoW: Rime, Killing Machine, Obliterate, Remorseless Winter. */
export const FROST_DK_TREE_V2: TalentNode[] = [
  {
    id: "frost_rime",
    name: "Rime",
    desc: "+10% damage vs chilled foes per rank.",
    rankDescs: ["+10% vs chilled.", "+20%.", "+30%."],
    maxRank: 3, row: 0, col: 2, requiresPoints: 0, scalePerRank: true,
    effect: { kind: "passive", hook: "vs_chilled", power: 10 },
  },
  {
    id: "frost_killing_machine",
    name: "Killing Machine",
    desc: "+4% crit per rank.",
    rankDescs: ["+4% crit.", "+8%.", "+12%."],
    maxRank: 3, row: 1, col: 1, requires: "frost_rime", requiresPoints: 3, scalePerRank: true,
    effect: { kind: "passive", hook: "crit_bonus", power: 4 },
  },
  {
    id: "frost_frozen_pulse",
    name: "Frozen Pulse",
    desc: "Frost Strike chill +1 turn per rank.",
    rankDescs: ["Chill +1t.", "+2t.", "+3t."],
    maxRank: 3, row: 1, col: 3, requires: "frost_rime", requiresPoints: 3, scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "froststrike", statusAmp: { kind: "chill", turnsDelta: 1 } } },
  },
  {
    id: "frost_howling_blast",
    name: "Howling Blast",
    desc: "Frost Strike +12% per rank.",
    rankDescs: ["Frost Strike +12%.", "+24%.", "+36%."],
    maxRank: 3, row: 2, col: 0, requires: "frost_killing_machine", requiresPoints: 8, scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "froststrike", multDelta: 0.12 } },
  },
  {
    id: "frost_gathering_storm",
    name: "Gathering Storm",
    desc: "Chill potency +0.05 per rank.",
    rankDescs: ["Chill hits harder.", "Stronger.", "Deep freeze pressure."],
    maxRank: 3, row: 2, col: 2, requires: ["frost_killing_machine", "frost_frozen_pulse"], requiresPoints: 8, scalePerRank: true,
    effect: { kind: "passive", hook: "dot_amp_chill", power: 1 },
  },
  {
    id: "frost_icy_talons",
    name: "Icy Talons",
    desc: "+2 ATK per rank.",
    rankDescs: ["+2 ATK.", "+4 ATK.", "+6 ATK."],
    maxRank: 3, row: 2, col: 4, requires: "frost_frozen_pulse", requiresPoints: 8, scalePerRank: true,
    effect: { kind: "stat", atk: 2 },
  },
  {
    id: "frost_pillar_of_frost",
    name: "Pillar of Frost",
    desc: "Obliterate +12% per rank.",
    rankDescs: ["Obliterate +12%.", "+24%.", "+36%."],
    maxRank: 3, row: 3, col: 1, requires: "frost_howling_blast", requiresPoints: 15, scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "spec_frost_dk", multDelta: 0.12 } },
  },
  {
    id: "frost_breath_of_sindragosa",
    name: "Breath of Sindragosa",
    desc: "Blood Boil applies chill per rank.",
    rankDescs: ["Boil chills.", "Strong chill.", "Deep chill (3t)."],
    maxRank: 3, row: 3, col: 3, requires: "frost_gathering_storm", requiresPoints: 15, scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "bloodboil", extraStatus: { kind: "chill", turns: 2, power: 1.2 } } },
  },
  {
    id: "frost_shattering_blade",
    name: "Shattering Blade",
    desc: "Death Strike +10% vs chilled per rank.",
    rankDescs: ["DS +10% vs chilled.", "+20%.", "+30%."],
    maxRank: 3, row: 4, col: 0, requires: "frost_pillar_of_frost", requiresPoints: 22, scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "deathstrike", bonusVsChillDelta: 0.1 } },
  },
  {
    id: "frost_inexorable_assault",
    name: "Inexorable Assault",
    desc: "Frost Strike +10% per rank.",
    rankDescs: ["Frost Strike +10%.", "+20%.", "+30%."],
    maxRank: 3, row: 4, col: 2, requires: ["frost_pillar_of_frost", "frost_breath_of_sindragosa"], requiresPoints: 22, scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "froststrike", multDelta: 0.1 } },
  },
  {
    id: "frost_cold_heart",
    name: "Cold Heart",
    desc: "+12% vs chilled per rank.",
    rankDescs: ["+12% vs chilled.", "+24%.", "+36%."],
    maxRank: 3, row: 4, col: 4, requires: "frost_icy_talons", requiresPoints: 22, scalePerRank: true,
    effect: { kind: "passive", hook: "vs_chilled", power: 12 },
  },
  {
    id: "frost_icebreaker",
    name: "Icebreaker",
    desc: "Death Strike +10% per rank.",
    rankDescs: ["Death Strike +10%.", "+20%.", "+30%."],
    maxRank: 3, row: 5, col: 1, requires: "frost_shattering_blade", requiresPoints: 30, scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "deathstrike", multDelta: 0.1 } },
  },
  {
    id: "frost_avalanche",
    name: "Avalanche",
    desc: "Blood Boil +10% per rank.",
    rankDescs: ["Blood Boil +10%.", "+20%.", "+30%."],
    maxRank: 3, row: 5, col: 3, requires: "frost_inexorable_assault", requiresPoints: 30, scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "bloodboil", multDelta: 0.1 } },
  },
  {
    id: "frost_winter_is_coming",
    name: "Winter is Coming",
    desc: "+4% crit per rank.",
    rankDescs: ["+4% crit.", "+8%.", "+12%."],
    maxRank: 3, row: 6, col: 0, requires: "frost_icebreaker", requiresPoints: 38, scalePerRank: true,
    effect: { kind: "passive", hook: "crit_bonus", power: 4 },
  },
  {
    id: "frost_runic_attenuation",
    name: "Runic Attenuation",
    desc: "Pass Turn ticks cooldowns.",
    maxRank: 1, row: 6, col: 4, requires: "frost_cold_heart", requiresPoints: 38,
    effect: { kind: "passive", hook: "pass_cd_tick", power: 1 },
  },
  {
    id: "frost_cap_obliterate",
    name: "Obliterate",
    desc: "★ Death Strike: 2.0× ATK, ×2 vs chilled.",
    maxRank: 1, row: 7, col: 0, requires: "frost_winter_is_coming", requiresPoints: 45,
    capstone: true, choiceGroup: "frost_capstone",
    effect: { kind: "ability", mod: { abilityId: "deathstrike", multDelta: 0.7, bonusVsChillDelta: 1.0, rename: "Obliterate", descOverride: "Rune obliteration. 2.0× ATK, shatters chill." } },
  },
  {
    id: "frost_cap_frostscythe",
    name: "Frostscythe",
    desc: "★ Frost Strike: 1.4× ATK, always chills.",
    maxRank: 1, row: 7, col: 2, requires: "frost_avalanche", requiresPoints: 45,
    capstone: true, choiceGroup: "frost_capstone",
    effect: { kind: "ability", mod: { abilityId: "froststrike", multDelta: 0.4, statusAmp: { kind: "chill", powerDelta: 0.2, turnsDelta: 1 }, rename: "Frostscythe", descOverride: "Scythe of frost. 1.4× ATK, deep chill." } },
  },
  {
    id: "frost_cap_remorseless",
    name: "Remorseless Winter",
    desc: "★ Blood Boil: 1.8× ATK, spreading chill.",
    maxRank: 1, row: 7, col: 4, requires: "frost_runic_attenuation", requiresPoints: 45,
    capstone: true, choiceGroup: "frost_capstone",
    effect: { kind: "ability", mod: { abilityId: "bloodboil", multDelta: 0.1, extraStatus: { kind: "chill", turns: 2, power: 1.3 }, rename: "Remorseless Winter", descOverride: "Winter storm. 1.8× ATK, chill spread." } },
  },
];
