import type { TalentNode } from "../talents";

/** Fury Warrior — WoW-inspired: Enrage, Bloodthirst, Rampage, Recklessness, whirlwind carnage. */
export const FURY_TREE_V2: TalentNode[] = [
  {
    id: "fury_frenzied_assault",
    name: "Frenzied Assault",
    desc: "All attacks leech +3% life per rank.",
    rankDescs: ["+3% lifesteal.", "+6% lifesteal.", "+9% lifesteal."],
    maxRank: 3,
    row: 0,
    col: 2,
    requiresPoints: 0,
    scalePerRank: true,
    effect: { kind: "passive", hook: "lifesteal_boost", power: 3 },
  },
  {
    id: "fury_enrage",
    name: "Enrage",
    desc: "Below 40% HP, deal +7% damage per rank.",
    rankDescs: ["+7% damage.", "+14% damage.", "+21% damage."],
    maxRank: 3,
    row: 1,
    col: 1,
    requires: "fury_frenzied_assault",
    requiresPoints: 3,
    scalePerRank: true,
    effect: { kind: "passive", hook: "low_hp_dmg", power: 7 },
  },
  {
    id: "fury_cruelty",
    name: "Cruelty",
    desc: "+2% crit per rank.",
    rankDescs: ["+2% crit.", "+4% crit.", "+6% crit."],
    maxRank: 3,
    row: 1,
    col: 3,
    requires: "fury_frenzied_assault",
    requiresPoints: 3,
    scalePerRank: true,
    effect: { kind: "passive", hook: "crit_bonus", power: 2 },
  },
  {
    id: "fury_meat_cleaver",
    name: "Meat Cleaver",
    desc: "Cleave cooldown −1 per rank (min 0).",
    rankDescs: ["Cleave CD −1.", "Cleave CD −2.", "Cleave CD −3."],
    maxRank: 3,
    row: 2,
    col: 0,
    requires: "fury_enrage",
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "cleave", cooldownDelta: -1 } },
  },
  {
    id: "fury_bloodcraze",
    name: "Bloodcraze",
    desc: "Kills empower your next hit (+8% per rank).",
    rankDescs: ["Kill frenzy +8%.", "Kill frenzy +16%.", "Kill frenzy +24%."],
    maxRank: 3,
    row: 2,
    col: 2,
    requires: ["fury_enrage", "fury_cruelty"],
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "passive", hook: "kill_frenzy", power: 8 },
  },
  {
    id: "fury_wrath_and_fury",
    name: "Wrath and Fury",
    desc: "+2 ATK per rank.",
    rankDescs: ["+2 ATK.", "+4 ATK.", "+6 ATK."],
    maxRank: 3,
    row: 2,
    col: 4,
    requires: "fury_cruelty",
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "stat", atk: 2 },
  },
  {
    id: "fury_rampage",
    name: "Rampage",
    desc: "Strike vs bleeding foes: +12% per rank.",
    rankDescs: ["Strike +12% vs bleed.", "Strike +24% vs bleed.", "Strike +36% vs bleed."],
    maxRank: 3,
    row: 3,
    col: 1,
    requires: "fury_meat_cleaver",
    requiresPoints: 15,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "strike", bonusVsBleedMult: 1.12 } },
  },
  {
    id: "fury_dragon_roar",
    name: "Dragon Roar",
    desc: "Cleave applies Burn (3t) — potency per rank.",
    rankDescs: ["Cleave + Burn 3/t.", "Cleave + Burn 4/t.", "Cleave + Burn 5/t."],
    maxRank: 3,
    row: 3,
    col: 3,
    requires: "fury_bloodcraze",
    requiresPoints: 15,
    scalePerRank: true,
    effect: {
      kind: "ability",
      mod: { abilityId: "cleave", extraStatus: { kind: "burn", turns: 3, power: 3 } },
    },
  },
  {
    id: "fury_recklessness",
    name: "Recklessness",
    desc: "+4% crit per rank.",
    rankDescs: ["+4% crit.", "+8% crit.", "+12% crit."],
    maxRank: 3,
    row: 4,
    col: 0,
    requires: "fury_rampage",
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "passive", hook: "crit_bonus", power: 4 },
  },
  {
    id: "fury_whirlwind",
    name: "Whirlwind",
    desc: "Cleave hits +10% harder per rank.",
    rankDescs: ["Cleave +10%.", "Cleave +20%.", "Cleave +30%."],
    maxRank: 3,
    row: 4,
    col: 2,
    requires: ["fury_rampage", "fury_dragon_roar"],
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "cleave", multDelta: 0.1 } },
  },
  {
    id: "fury_massacre",
    name: "Massacre",
    desc: "Burn ticks deal +1 damage per rank.",
    rankDescs: ["Burn +1/tick.", "Burn +2/tick.", "Burn +3/tick."],
    maxRank: 3,
    row: 4,
    col: 4,
    requires: "fury_wrath_and_fury",
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "passive", hook: "dot_amp_burn", power: 1 },
  },
  {
    id: "fury_bloodthirst_mastery",
    name: "Bloodthirst",
    desc: "Signature Bloodthirst +10% per rank.",
    rankDescs: ["Bloodthirst +10%.", "Bloodthirst +20%.", "Bloodthirst +30%."],
    maxRank: 3,
    row: 5,
    col: 1,
    requires: "fury_whirlwind",
    requiresPoints: 30,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "spec_fury", multDelta: 0.1, lifestealDelta: 0.05 } },
  },
  {
    id: "fury_fresh_meat",
    name: "Fresh Meat",
    desc: "Strike +10% damage per rank.",
    rankDescs: ["Strike +10%.", "Strike +20%.", "Strike +30%."],
    maxRank: 3,
    row: 5,
    col: 3,
    requires: "fury_dragon_roar",
    requiresPoints: 30,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "strike", multDelta: 0.1 } },
  },
  {
    id: "fury_titanic_rage",
    name: "Titanic Rage",
    desc: "+5 Max HP per rank.",
    rankDescs: ["+5 Max HP.", "+10 Max HP.", "+15 Max HP."],
    maxRank: 3,
    row: 6,
    col: 0,
    requires: "fury_recklessness",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "stat", maxHp: 5 },
  },
  {
    id: "fury_odyns_fury",
    name: "Odyn's Fury",
    desc: "Cleave +15% and lifesteal +5% per rank.",
    rankDescs: ["Cleave +15%, +5% leech.", "Cleave +30%, +10% leech.", "Cleave +45%, +15% leech."],
    maxRank: 3,
    row: 6,
    col: 2,
    requires: "fury_bloodthirst_mastery",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "cleave", multDelta: 0.15, lifestealDelta: 0.05 } },
  },
  {
    id: "fury_warpaint",
    name: "Warpaint",
    desc: "Pass Turn ticks all cooldowns (rank 1). +3% crit per extra rank.",
    maxRank: 1,
    row: 6,
    col: 4,
    requires: "fury_massacre",
    requiresPoints: 38,
    effect: { kind: "passive", hook: "pass_cd_tick", power: 1 },
  },
  {
    id: "fury_cap_bloodthirst",
    name: "Bloodthirst",
    desc: "★ Strike becomes Bloodthirst: 1.4× ATK, 35% lifesteal.",
    maxRank: 1,
    row: 7,
    col: 0,
    requires: "fury_titanic_rage",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "fury_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "strike",
        multDelta: 0.4,
        lifestealDelta: 0.35,
        rename: "Bloodthirst",
        descOverride: "Ravenous strike. 1.4× ATK, heal 35% of damage.",
      },
    },
  },
  {
    id: "fury_cap_raging_blow",
    name: "Raging Blow",
    desc: "★ Cleave hits twice as hard: 2.4× ATK.",
    maxRank: 1,
    row: 7,
    col: 2,
    requires: "fury_odyns_fury",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "fury_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "cleave",
        multDelta: 0.8,
        rename: "Raging Blow",
        descOverride: "Twin cleave. 2.4× ATK + bleed.",
      },
    },
  },
  {
    id: "fury_cap_bladestorm",
    name: "Bladestorm",
    desc: "★ Cleave: 2.0× ATK, applies Burn and Bleed.",
    maxRank: 1,
    row: 7,
    col: 4,
    requires: "fury_warpaint",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "fury_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "cleave",
        multDelta: 0.4,
        extraStatus: { kind: "burn", turns: 3, power: 4 },
        statusAmp: { kind: "bleed", powerDelta: 2, turnsDelta: 1 },
        rename: "Bladestorm",
        descOverride: "Whirlwind of steel. 2.0× ATK, burn + bleed.",
      },
    },
  },
];
