import type { TalentNode } from "../talents";

/** Havoc Demon Hunter — WoW: Demon Blades, Cycle of Hatred, Eye Beam, Metamorphosis, fel chaos. */
export const HAVOC_TREE_V2: TalentNode[] = [
  {
    id: "havoc_demon_blades",
    name: "Demon Blades",
    desc: "Chaos Strike +5% damage per rank.",
    rankDescs: ["Chaos Strike +5%.", "Chaos Strike +10%.", "Chaos Strike +15%."],
    maxRank: 3,
    row: 0,
    col: 2,
    requiresPoints: 0,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "chaosstrike", multDelta: 0.05 } },
  },
  {
    id: "havoc_critical_chaos",
    name: "Critical Chaos",
    desc: "+5% crit per rank.",
    rankDescs: ["+5% crit.", "+10% crit.", "+15% crit."],
    maxRank: 3,
    row: 1,
    col: 1,
    requires: "havoc_demon_blades",
    requiresPoints: 3,
    scalePerRank: true,
    effect: { kind: "passive", hook: "crit_bonus", power: 5 },
  },
  {
    id: "havoc_burning_hatred",
    name: "Burning Hatred",
    desc: "Burn ticks +1 damage per rank.",
    rankDescs: ["Burn +1/t.", "Burn +2/t.", "Burn +3/t."],
    maxRank: 3,
    row: 1,
    col: 3,
    requires: "havoc_demon_blades",
    requiresPoints: 3,
    scalePerRank: true,
    effect: { kind: "passive", hook: "dot_amp_burn", power: 1 },
  },
  {
    id: "havoc_trail_of_ruin",
    name: "Trail of Ruin",
    desc: "Fel Rush burn +1 power per rank.",
    rankDescs: ["Fel Rush burn +1.", "Fel Rush burn +2.", "Fel Rush burn +3."],
    maxRank: 3,
    row: 2,
    col: 0,
    requires: "havoc_critical_chaos",
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "felrush", statusAmp: { kind: "burn", powerDelta: 1 } } },
  },
  {
    id: "havoc_chaos_theory",
    name: "Chaos Theory",
    desc: "Fel Rush CD −1 per rank (min 0).",
    rankDescs: ["Fel Rush CD −1.", "Fel Rush CD −2.", "Fel Rush CD −3."],
    maxRank: 3,
    row: 2,
    col: 2,
    requires: ["havoc_critical_chaos", "havoc_burning_hatred"],
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "felrush", cooldownDelta: -1 } },
  },
  {
    id: "havoc_initiative",
    name: "Initiative",
    desc: "+2 ATK per rank.",
    rankDescs: ["+2 ATK.", "+4 ATK.", "+6 ATK."],
    maxRank: 3,
    row: 2,
    col: 4,
    requires: "havoc_burning_hatred",
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "stat", atk: 2 },
  },
  {
    id: "havoc_first_blood",
    name: "First Blood",
    desc: "Eye Beam +10% damage per rank.",
    rankDescs: ["Eye Beam +10%.", "Eye Beam +20%.", "Eye Beam +30%."],
    maxRank: 3,
    row: 3,
    col: 1,
    requires: "havoc_trail_of_ruin",
    requiresPoints: 15,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "eyebeam", multDelta: 0.1 } },
  },
  {
    id: "havoc_cycle_of_hatred",
    name: "Cycle of Hatred",
    desc: "Kills empower next hit (+8% per rank).",
    rankDescs: ["Kill frenzy +8%.", "Kill frenzy +16%.", "Kill frenzy +24%."],
    maxRank: 3,
    row: 3,
    col: 3,
    requires: "havoc_chaos_theory",
    requiresPoints: 15,
    scalePerRank: true,
    effect: { kind: "passive", hook: "kill_frenzy", power: 8 },
  },
  {
    id: "havoc_blind_fury",
    name: "Blind Fury",
    desc: "Chaos Strike +8% and +5% crit per rank.",
    rankDescs: ["Chaos Strike +8%, +5% crit.", "+16%, +10% crit.", "+24%, +15% crit."],
    maxRank: 3,
    row: 4,
    col: 0,
    requires: "havoc_first_blood",
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "chaosstrike", multDelta: 0.08, bonusCritPct: 5 } },
  },
  {
    id: "havoc_eye_beam_mastery",
    name: "Eye Beam",
    desc: "Signature Eye Beam +10% per rank.",
    rankDescs: ["Eye Beam +10%.", "Eye Beam +20%.", "Eye Beam +30%."],
    maxRank: 3,
    row: 4,
    col: 2,
    requires: ["havoc_first_blood", "havoc_cycle_of_hatred"],
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "spec_havoc", multDelta: 0.1, bonusCritPct: 5 } },
  },
  {
    id: "havoc_vs_burning",
    name: "Chaos Brand",
    desc: "+10% damage vs burning foes per rank.",
    rankDescs: ["+10% vs burn.", "+20% vs burn.", "+30% vs burn."],
    maxRank: 3,
    row: 4,
    col: 4,
    requires: "havoc_initiative",
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "passive", hook: "vs_burning", power: 10 },
  },
  {
    id: "havoc_chaotic_transformation",
    name: "Chaotic Transformation",
    desc: "Eye Beam +15% and ignores guard at rank 3.",
    rankDescs: ["Eye Beam +15%.", "Eye Beam +30%.", "Eye Beam +45%, pierces guard."],
    maxRank: 3,
    row: 5,
    col: 1,
    requires: "havoc_eye_beam_mastery",
    requiresPoints: 30,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "eyebeam", multDelta: 0.15, ignoreGuard: true } },
  },
  {
    id: "havoc_fel_barrage",
    name: "Fel Barrage",
    desc: "Fel Rush +10% damage per rank.",
    rankDescs: ["Fel Rush +10%.", "Fel Rush +20%.", "Fel Rush +30%."],
    maxRank: 3,
    row: 5,
    col: 3,
    requires: "havoc_cycle_of_hatred",
    requiresPoints: 30,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "felrush", multDelta: 0.1 } },
  },
  {
    id: "havoc_demonic",
    name: "Demonic",
    desc: "+4% crit per rank.",
    rankDescs: ["+4% crit.", "+8% crit.", "+12% crit."],
    maxRank: 3,
    row: 6,
    col: 0,
    requires: "havoc_blind_fury",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "passive", hook: "crit_bonus", power: 4 },
  },
  {
    id: "havoc_inner_demon",
    name: "Inner Demon",
    desc: "Chaos Strike +12% per rank.",
    rankDescs: ["Chaos Strike +12%.", "Chaos Strike +24%.", "Chaos Strike +36%."],
    maxRank: 3,
    row: 6,
    col: 2,
    requires: "havoc_chaotic_transformation",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "chaosstrike", multDelta: 0.12 } },
  },
  {
    id: "havoc_unbound_chaos",
    name: "Unbound Chaos",
    desc: "Crits ignite for +1 burn per rank.",
    rankDescs: ["Crit burn 3/t.", "Crit burn 4/t.", "Crit burn 5/t."],
    maxRank: 3,
    row: 6,
    col: 4,
    requires: "havoc_vs_burning",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "passive", hook: "crit_dot_burn", power: 3 },
  },
  {
    id: "havoc_cap_blade_dance",
    name: "Blade Dance",
    desc: "★ Chaos Strike: 1.5× ATK, +25% crit.",
    maxRank: 1,
    row: 7,
    col: 0,
    requires: "havoc_demonic",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "havoc_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "chaosstrike",
        multDelta: 0.4,
        bonusCritPct: 25,
        rename: "Blade Dance",
        descOverride: "Glaive dance. 1.5× ATK, +25% crit.",
      },
    },
  },
  {
    id: "havoc_cap_metamorphosis",
    name: "Metamorphosis",
    desc: "★ Eye Beam: 2.6× MAG, pierces guard.",
    maxRank: 1,
    row: 7,
    col: 2,
    requires: "havoc_inner_demon",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "havoc_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "eyebeam",
        multDelta: 0.4,
        ignoreGuard: true,
        rename: "Metamorphosis",
        descOverride: "Demon form. 2.6× MAG, pierces guard.",
      },
    },
  },
  {
    id: "havoc_cap_essence_break",
    name: "Essence Break",
    desc: "★ Fel Rush: 2.0× MAG, brutal burn.",
    maxRank: 1,
    row: 7,
    col: 4,
    requires: "havoc_unbound_chaos",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "havoc_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "felrush",
        multDelta: 0.4,
        statusAmp: { kind: "burn", powerDelta: 4 },
        rename: "Essence Break",
        descOverride: "Fel eruption. 2.0× MAG, heavy burn.",
      },
    },
  },
];
