import type { TalentNode } from "../talents";

/** Holy Priest — WoW: Renewed Faith, Holy Fire, Serendipity, Holy Word: Serenity, Apotheosis. */
export const HOLY_TREE_V2: TalentNode[] = [
  {
    id: "holy_renewed_faith",
    name: "Renewed Faith",
    desc: "Renew heals +1 per tick per rank.",
    rankDescs: ["Renew +1/t.", "Renew +2/t.", "Renew +3/t."],
    maxRank: 3,
    row: 0,
    col: 2,
    requiresPoints: 0,
    scalePerRank: true,
    effect: { kind: "passive", hook: "hot_amp", power: 1 },
  },
  {
    id: "holy_guardian_spirit",
    name: "Guardian Spirit",
    desc: "Below 40% HP, deal +8% damage per rank.",
    rankDescs: ["+8% damage.", "+16% damage.", "+24% damage."],
    maxRank: 3,
    row: 1,
    col: 1,
    requires: "holy_renewed_faith",
    requiresPoints: 3,
    scalePerRank: true,
    effect: { kind: "passive", hook: "low_hp_dmg", power: 8 },
  },
  {
    id: "holy_holy_fire",
    name: "Holy Fire",
    desc: "Smite applies burn — potency per rank.",
    rankDescs: ["Smite + Burn 3/t.", "Burn 4/t.", "Burn 5/t."],
    maxRank: 3,
    row: 1,
    col: 3,
    requires: "holy_renewed_faith",
    requiresPoints: 3,
    scalePerRank: true,
    effect: {
      kind: "ability",
      mod: { abilityId: "smite", extraStatus: { kind: "burn", turns: 3, power: 3 } },
    },
  },
  {
    id: "holy_sanctified_prayers",
    name: "Sanctified Prayers",
    desc: "Renew +1 turn per rank.",
    rankDescs: ["Renew +1 turn.", "+2 turns.", "+3 turns."],
    maxRank: 3,
    row: 2,
    col: 0,
    requires: "holy_guardian_spirit",
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "renew", hotTurnsDelta: 1 } },
  },
  {
    id: "holy_divine_fury",
    name: "Divine Fury",
    desc: "+2 MAG per rank.",
    rankDescs: ["+2 MAG.", "+4 MAG.", "+6 MAG."],
    maxRank: 3,
    row: 2,
    col: 2,
    requires: ["holy_guardian_spirit", "holy_holy_fire"],
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "stat", mag: 2 },
  },
  {
    id: "holy_burning_light",
    name: "Burning Light",
    desc: "+8% damage vs burning foes per rank.",
    rankDescs: ["+8% vs burn.", "+16% vs burn.", "+24% vs burn."],
    maxRank: 3,
    row: 2,
    col: 4,
    requires: "holy_holy_fire",
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "passive", hook: "vs_burning", power: 8 },
  },
  {
    id: "holy_chastise",
    name: "Holy Word: Chastise",
    desc: "Smite +10% damage per rank.",
    rankDescs: ["Smite +10%.", "Smite +20%.", "Smite +30%."],
    maxRank: 3,
    row: 3,
    col: 1,
    requires: "holy_sanctified_prayers",
    requiresPoints: 15,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "smite", multDelta: 0.1 } },
  },
  {
    id: "holy_empowered_renew",
    name: "Empowered Renew",
    desc: "Renew +1 heal/tick per rank.",
    rankDescs: ["Renew +1/t.", "Renew +2/t.", "Renew +3/t."],
    maxRank: 3,
    row: 3,
    col: 3,
    requires: "holy_divine_fury",
    requiresPoints: 15,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "renew", hotPowerDelta: 1 } },
  },
  {
    id: "holy_lightwell",
    name: "Lightwell",
    desc: "Smite leeches +5% per rank.",
    rankDescs: ["Smite +5% leech.", "+10% leech.", "+15% leech."],
    maxRank: 3,
    row: 4,
    col: 0,
    requires: "holy_chastise",
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "smite", lifestealDelta: 0.05 } },
  },
  {
    id: "holy_serendipity",
    name: "Serendipity",
    desc: "Pass Turn ticks cooldowns once.",
    maxRank: 1,
    row: 4,
    col: 2,
    requires: ["holy_chastise", "holy_empowered_renew"],
    requiresPoints: 22,
    effect: { kind: "passive", hook: "pass_cd_tick", power: 1 },
  },
  {
    id: "holy_cauterizing_shadow",
    name: "Cauterizing Shadows",
    desc: "Burn ticks +1 per rank.",
    rankDescs: ["Burn +1/t.", "Burn +2/t.", "Burn +3/t."],
    maxRank: 3,
    row: 4,
    col: 4,
    requires: "holy_burning_light",
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "passive", hook: "dot_amp_burn", power: 1 },
  },
  {
    id: "holy_answered_prayers",
    name: "Answered Prayers",
    desc: "SW:Pain +10% per rank.",
    rankDescs: ["SW:Pain +10%.", "SW:Pain +20%.", "SW:Pain +30%."],
    maxRank: 3,
    row: 5,
    col: 1,
    requires: "holy_serendipity",
    requiresPoints: 30,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "swp", multDelta: 0.1 } },
  },
  {
    id: "holy_oracle",
    name: "Oracle",
    desc: "+3% crit per rank.",
    rankDescs: ["+3% crit.", "+6% crit.", "+9% crit."],
    maxRank: 3,
    row: 5,
    col: 3,
    requires: "holy_empowered_renew",
    requiresPoints: 30,
    scalePerRank: true,
    effect: { kind: "passive", hook: "crit_bonus", power: 3 },
  },
  {
    id: "holy_sanctify",
    name: "Sanctify",
    desc: "Renew +2 heal/tick per rank.",
    rankDescs: ["Renew +2/t.", "Renew +4/t.", "Renew +6/t."],
    maxRank: 3,
    row: 6,
    col: 0,
    requires: "holy_lightwell",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "renew", hotPowerDelta: 2 } },
  },
  {
    id: "holy_salvation_prep",
    name: "Holy Word: Salvation",
    desc: "Smite +12% per rank.",
    rankDescs: ["Smite +12%.", "Smite +24%.", "Smite +36%."],
    maxRank: 3,
    row: 6,
    col: 2,
    requires: "holy_answered_prayers",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "smite", multDelta: 0.12, lifestealDelta: 0.05 } },
  },
  {
    id: "holy_apotheosis_prep",
    name: "Apotheosis",
    desc: "SW:Pain burn +1 power per rank.",
    rankDescs: ["SW:Pain burn +1.", "+2.", "+3."],
    maxRank: 3,
    row: 6,
    col: 4,
    requires: "holy_cauterizing_shadow",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "swp", statusAmp: { kind: "burn", powerDelta: 1 } } },
  },
  {
    id: "holy_cap_serenity",
    name: "Holy Word: Serenity",
    desc: "★ Renew: 9 HP/tick, 6 turns.",
    maxRank: 1,
    row: 7,
    col: 0,
    requires: "holy_sanctify",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "holy_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "renew",
        hotPowerDelta: 6,
        hotTurnsDelta: 2,
        rename: "Holy Word: Serenity",
        descOverride: "Powerful renewal. 9+ HP/tick for 6 turns.",
      },
    },
  },
  {
    id: "holy_cap_salvation",
    name: "Holy Word: Salvation",
    desc: "★ Smite: 1.4× MAG, heals 40% dealt.",
    maxRank: 1,
    row: 7,
    col: 2,
    requires: "holy_salvation_prep",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "holy_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "smite",
        multDelta: 0.4,
        lifestealDelta: 0.4,
        rename: "Holy Word: Salvation",
        descOverride: "Holy smite. 1.4× MAG, heal 40% damage.",
      },
    },
  },
  {
    id: "holy_cap_apotheosis",
    name: "Apotheosis",
    desc: "★ SW:Pain: 1.5× MAG, prolonged burn.",
    maxRank: 1,
    row: 7,
    col: 4,
    requires: "holy_apotheosis_prep",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "holy_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "swp",
        multDelta: 0.3,
        statusAmp: { kind: "burn", turnsDelta: 2, powerDelta: 2 },
        rename: "Apotheosis",
        descOverride: "1.5× MAG, prolonged agony burn.",
      },
    },
  },
];
