import type { TalentNode } from "../talents";

/** Fire Mage — WoW: Ignite, Hot Streak, Combustion, Pyroblast, Phoenix Flames. */
export const FIRE_MAGE_TREE_V2: TalentNode[] = [
  {
    id: "fire_ignite",
    name: "Ignite",
    desc: "Burn ticks +1 damage per rank.",
    rankDescs: ["Burn +1/t.", "Burn +2/t.", "Burn +3/t."],
    maxRank: 3,
    row: 0,
    col: 2,
    requiresPoints: 0,
    scalePerRank: true,
    effect: { kind: "passive", hook: "dot_amp_burn", power: 1 },
  },
  {
    id: "fire_pyromaniac",
    name: "Pyromaniac",
    desc: "+8% damage vs burning foes per rank.",
    rankDescs: ["+8% vs burn.", "+16% vs burn.", "+24% vs burn."],
    maxRank: 3,
    row: 1,
    col: 1,
    requires: "fire_ignite",
    requiresPoints: 3,
    scalePerRank: true,
    effect: { kind: "passive", hook: "vs_burning", power: 8 },
  },
  {
    id: "fire_hot_streak",
    name: "Hot Streak",
    desc: "+3% crit per rank.",
    rankDescs: ["+3% crit.", "+6% crit.", "+9% crit."],
    maxRank: 3,
    row: 1,
    col: 3,
    requires: "fire_ignite",
    requiresPoints: 3,
    scalePerRank: true,
    effect: { kind: "passive", hook: "crit_bonus", power: 3 },
  },
  {
    id: "fire_living_bomb",
    name: "Living Bomb",
    desc: "Fireball burn +1 power per rank.",
    rankDescs: ["Fireball burn +1.", "Fireball burn +2.", "Fireball burn +3."],
    maxRank: 3,
    row: 2,
    col: 0,
    requires: "fire_pyromaniac",
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "fireball", statusAmp: { kind: "burn", powerDelta: 1 } } },
  },
  {
    id: "fire_combustion",
    name: "Combustion",
    desc: "Crits ignite (potency per rank).",
    rankDescs: ["Crit burn 3/t.", "Crit burn 4/t.", "Crit burn 5/t."],
    maxRank: 3,
    row: 2,
    col: 2,
    requires: ["fire_pyromaniac", "fire_hot_streak"],
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "passive", hook: "crit_dot_burn", power: 3 },
  },
  {
    id: "fire_flame_on",
    name: "Flame On",
    desc: "+2 MAG per rank.",
    rankDescs: ["+2 MAG.", "+4 MAG.", "+6 MAG."],
    maxRank: 3,
    row: 2,
    col: 4,
    requires: "fire_hot_streak",
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "stat", mag: 2 },
  },
  {
    id: "fire_kindling",
    name: "Kindling",
    desc: "Fireball CD −1 per rank (min 0).",
    rankDescs: ["Fireball CD −1.", "Fireball CD −2.", "Fireball CD −3."],
    maxRank: 3,
    row: 3,
    col: 1,
    requires: "fire_living_bomb",
    requiresPoints: 15,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "fireball", cooldownDelta: -1 } },
  },
  {
    id: "fire_flame_patch",
    name: "Flame Patch",
    desc: "Frostbolt applies burn per rank.",
    rankDescs: ["Frostbolt + burn.", "Stronger burn.", "Heavy burn."],
    maxRank: 3,
    row: 3,
    col: 3,
    requires: "fire_combustion",
    requiresPoints: 15,
    scalePerRank: true,
    effect: {
      kind: "ability",
      mod: { abilityId: "frostbolt", extraStatus: { kind: "burn", turns: 2, power: 3 } },
    },
  },
  {
    id: "fire_firestarter",
    name: "Firestarter",
    desc: "Fireball +10% damage per rank.",
    rankDescs: ["Fireball +10%.", "Fireball +20%.", "Fireball +30%."],
    maxRank: 3,
    row: 4,
    col: 0,
    requires: "fire_kindling",
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "fireball", multDelta: 0.1 } },
  },
  {
    id: "fire_cinderstorm",
    name: "Cinderstorm",
    desc: "Kills empower next hit (+7% per rank).",
    rankDescs: ["Kill frenzy +7%.", "Kill frenzy +14%.", "Kill frenzy +21%."],
    maxRank: 3,
    row: 4,
    col: 2,
    requires: ["fire_kindling", "fire_flame_patch"],
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "passive", hook: "kill_frenzy", power: 7 },
  },
  {
    id: "fire_mastery",
    name: "Mastery: Ignite",
    desc: "Burn ticks +1 per rank (stacks with Ignite).",
    rankDescs: ["Burn +1/t.", "Burn +2/t.", "Burn +3/t."],
    maxRank: 3,
    row: 4,
    col: 4,
    requires: "fire_flame_on",
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "passive", hook: "dot_amp_burn", power: 1 },
  },
  {
    id: "fire_scald",
    name: "Scald",
    desc: "Frostbolt +8% vs burning per rank.",
    rankDescs: ["Frostbolt +8% vs burn.", "+16% vs burn.", "+24% vs burn."],
    maxRank: 3,
    row: 5,
    col: 1,
    requires: "fire_cinderstorm",
    requiresPoints: 30,
    scalePerRank: true,
    effect: { kind: "passive", hook: "vs_burning", power: 8 },
  },
  {
    id: "fire_meteor_prep",
    name: "Meteor",
    desc: "Nova applies heavy burn per rank.",
    rankDescs: ["Nova + burn.", "Stronger burn.", "Brutal burn."],
    maxRank: 3,
    row: 5,
    col: 3,
    requires: "fire_flame_patch",
    requiresPoints: 30,
    scalePerRank: true,
    effect: {
      kind: "ability",
      mod: { abilityId: "nova", extraStatus: { kind: "burn", turns: 3, power: 4 } },
    },
  },
  {
    id: "fire_phoenix_reborn",
    name: "Phoenix Reborn",
    desc: "+4% crit per rank.",
    rankDescs: ["+4% crit.", "+8% crit.", "+12% crit."],
    maxRank: 3,
    row: 6,
    col: 0,
    requires: "fire_firestarter",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "passive", hook: "crit_bonus", power: 4 },
  },
  {
    id: "fire_sun_kings_fury",
    name: "Sun King's Fury",
    desc: "Fireball +12% per rank.",
    rankDescs: ["Fireball +12%.", "Fireball +24%.", "Fireball +36%."],
    maxRank: 3,
    row: 6,
    col: 2,
    requires: "fire_scald",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "fireball", multDelta: 0.12 } },
  },
  {
    id: "fire_flamestrike",
    name: "Flamestrike",
    desc: "Unlock Flamestrike — fire rains on ALL foes.",
    maxRank: 1,
    row: 6,
    col: 4,
    requires: "fire_mastery",
    requiresPoints: 38,
    effect: { kind: "grant_ability", abilityId: "flamestrike" },
  },
  {
    id: "fire_cap_pyroblast",
    name: "Pyroblast",
    desc: "★ Fireball: 2.0× MAG, brutal burn.",
    maxRank: 1,
    row: 7,
    col: 0,
    requires: "fire_phoenix_reborn",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "fire_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "fireball",
        multDelta: 0.5,
        statusAmp: { kind: "burn", powerDelta: 3, turnsDelta: 1 },
        rename: "Pyroblast",
        descOverride: "Massive fireball. 2.0× MAG, heavy burn.",
      },
    },
  },
  {
    id: "fire_cap_phoenix_flames",
    name: "Phoenix Flames",
    desc: "★ Frostbolt: 1.2× MAG, instant burn.",
    maxRank: 1,
    row: 7,
    col: 2,
    requires: "fire_sun_kings_fury",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "fire_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "frostbolt",
        multDelta: 0.2,
        cooldownDelta: -99,
        extraStatus: { kind: "burn", turns: 3, power: 4 },
        rename: "Phoenix Flames",
        descOverride: "Reborn flame. 1.2× MAG + burn, no CD.",
      },
    },
  },
  {
    id: "fire_cap_meteor",
    name: "Meteor",
    desc: "★ Frost Nova: stun + heavy burn (4t).",
    maxRank: 1,
    row: 7,
    col: 4,
    requires: "fire_flamestrike",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "fire_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "nova",
        extraStatus: { kind: "burn", turns: 4, power: 6 },
        rename: "Meteor",
        descOverride: "Meteor freeze. Stun + heavy burn (4t).",
      },
    },
  },
];
