import type { TalentNode } from "../talents";

/** Arcane Mage — WoW: Arcane Familiar, Touch of the Magi, Arcane Blast, Barrage, Presence of Mind. */
export const ARCANE_MAGE_TREE_V2: TalentNode[] = [
  {
    id: "arcane_familiar",
    name: "Arcane Familiar",
    desc: "Pass Turn ticks all cooldowns once.",
    maxRank: 1,
    row: 0,
    col: 2,
    requiresPoints: 0,
    effect: { kind: "passive", hook: "pass_cd_tick", power: 1 },
  },
  {
    id: "arcane_nether_precision",
    name: "Nether Precision",
    desc: "Frostbolt +7% damage per rank.",
    rankDescs: ["Frostbolt +7%.", "Frostbolt +14%.", "Frostbolt +21%."],
    maxRank: 3,
    row: 1,
    col: 1,
    requires: "arcane_familiar",
    requiresPoints: 3,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "frostbolt", multDelta: 0.07 } },
  },
  {
    id: "arcane_concentration",
    name: "Concentration",
    desc: "+3% crit per rank.",
    rankDescs: ["+3% crit.", "+6% crit.", "+9% crit."],
    maxRank: 3,
    row: 1,
    col: 3,
    requires: "arcane_familiar",
    requiresPoints: 3,
    scalePerRank: true,
    effect: { kind: "passive", hook: "crit_bonus", power: 3 },
  },
  {
    id: "arcane_missiles",
    name: "Arcane Missiles",
    desc: "Fireball CD −1 per rank (min 0).",
    rankDescs: ["Fireball CD −1.", "Fireball CD −2.", "Fireball CD −3."],
    maxRank: 3,
    row: 2,
    col: 0,
    requires: "arcane_nether_precision",
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "fireball", cooldownDelta: -1 } },
  },
  {
    id: "arcane_mana_adept",
    name: "Mana Adept",
    desc: "+2 MAG per rank.",
    rankDescs: ["+2 MAG.", "+4 MAG.", "+6 MAG."],
    maxRank: 3,
    row: 2,
    col: 2,
    requires: ["arcane_nether_precision", "arcane_concentration"],
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "stat", mag: 2 },
  },
  {
    id: "arcane_echo",
    name: "Arcane Echo",
    desc: "Kills empower next hit (+7% per rank).",
    rankDescs: ["Kill frenzy +7%.", "Kill frenzy +14%.", "Kill frenzy +21%."],
    maxRank: 3,
    row: 2,
    col: 4,
    requires: "arcane_concentration",
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "passive", hook: "kill_frenzy", power: 7 },
  },
  {
    id: "arcane_touch",
    name: "Touch of the Magi",
    desc: "Fireball +12% damage per rank.",
    rankDescs: ["Fireball +12%.", "Fireball +24%.", "Fireball +36%."],
    maxRank: 3,
    row: 3,
    col: 1,
    requires: "arcane_missiles",
    requiresPoints: 15,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "fireball", multDelta: 0.12 } },
  },
  {
    id: "arcane_orb",
    name: "Arcane Orb",
    desc: "Frostbolt +10% per rank.",
    rankDescs: ["Frostbolt +10%.", "Frostbolt +20%.", "Frostbolt +30%."],
    maxRank: 3,
    row: 3,
    col: 3,
    requires: "arcane_mana_adept",
    requiresPoints: 15,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "frostbolt", multDelta: 0.1 } },
  },
  {
    id: "arcane_surge",
    name: "Arcane Surge",
    desc: "+4% crit per rank.",
    rankDescs: ["+4% crit.", "+8% crit.", "+12% crit."],
    maxRank: 3,
    row: 4,
    col: 0,
    requires: "arcane_touch",
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "passive", hook: "crit_bonus", power: 4 },
  },
  {
    id: "arcane_harmony",
    name: "Arcane Harmony",
    desc: "Fireball +10% and ignores guard at rank 3.",
    rankDescs: ["Fireball +10%.", "Fireball +20%.", "Fireball +30%, pierces guard."],
    maxRank: 3,
    row: 4,
    col: 2,
    requires: ["arcane_touch", "arcane_orb"],
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "fireball", multDelta: 0.1, ignoreGuard: true } },
  },
  {
    id: "arcane_reverberate",
    name: "Reverberate",
    desc: "+8% vs chilled per rank.",
    rankDescs: ["+8% vs chill.", "+16% vs chill.", "+24% vs chill."],
    maxRank: 3,
    row: 4,
    col: 4,
    requires: "arcane_echo",
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "passive", hook: "vs_chilled", power: 8 },
  },
  {
    id: "arcane_blast_prep",
    name: "Arcane Blast",
    desc: "Frostbolt +15% per rank.",
    rankDescs: ["Frostbolt +15%.", "Frostbolt +30%.", "Frostbolt +45%."],
    maxRank: 3,
    row: 5,
    col: 1,
    requires: "arcane_harmony",
    requiresPoints: 30,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "frostbolt", multDelta: 0.15 } },
  },
  {
    id: "arcane_barrage_prep",
    name: "Arcane Barrage",
    desc: "Fireball +15% per rank.",
    rankDescs: ["Fireball +15%.", "Fireball +30%.", "Fireball +45%."],
    maxRank: 3,
    row: 5,
    col: 3,
    requires: "arcane_orb",
    requiresPoints: 30,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "fireball", multDelta: 0.15 } },
  },
  {
    id: "arcane_intellect",
    name: "Arcane Intellect",
    desc: "+3 MAG per rank.",
    rankDescs: ["+3 MAG.", "+6 MAG.", "+9 MAG."],
    maxRank: 3,
    row: 6,
    col: 0,
    requires: "arcane_surge",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "stat", mag: 3 },
  },
  {
    id: "arcane_evocation",
    name: "Evocation",
    desc: "Nova CD −1 per rank (min 0).",
    rankDescs: ["Nova CD −1.", "Nova CD −2.", "Nova CD −3."],
    maxRank: 3,
    row: 6,
    col: 2,
    requires: "arcane_blast_prep",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "nova", cooldownDelta: -1 } },
  },
  {
    id: "arcane_momentum",
    name: "Momentum",
    desc: "Chill potency +0.1 per rank.",
    rankDescs: ["Chill +0.1.", "Chill +0.2.", "Chill +0.3."],
    maxRank: 3,
    row: 6,
    col: 4,
    requires: "arcane_reverberate",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "passive", hook: "dot_amp_chill", power: 1 },
  },
  {
    id: "arcane_cap_blast",
    name: "Arcane Blast",
    desc: "★ Frostbolt: 1.8× MAG, CD 1.",
    maxRank: 1,
    row: 7,
    col: 0,
    requires: "arcane_intellect",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "arcane_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "frostbolt",
        multDelta: 0.8,
        cooldownDelta: 1,
        rename: "Arcane Blast",
        descOverride: "Pure mana bolt. 1.8× MAG, CD 1.",
      },
    },
  },
  {
    id: "arcane_cap_barrage",
    name: "Arcane Barrage",
    desc: "★ Fireball: 2.2× MAG, pierces guard.",
    maxRank: 1,
    row: 7,
    col: 2,
    requires: "arcane_evocation",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "arcane_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "fireball",
        multDelta: 0.7,
        ignoreGuard: true,
        rename: "Arcane Barrage",
        descOverride: "Arcane salvo. 2.2× MAG, pierces guard.",
      },
    },
  },
  {
    id: "arcane_cap_presence",
    name: "Presence of Mind",
    desc: "★ Frostbolt: 1.6× MAG, focused bolt.",
    maxRank: 1,
    row: 7,
    col: 4,
    requires: "arcane_momentum",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "arcane_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "frostbolt",
        multDelta: 0.6,
        rename: "Presence of Mind",
        descOverride: "Focused bolt. 1.6× MAG.",
      },
    },
  },
];
