import type { TalentNode } from "../talents";

/** Frost Mage — WoW: Shatter, Brain Freeze, Glacial Spike, Flurry, Frozen Orb. */
export const FROST_MAGE_TREE_V2: TalentNode[] = [
  {
    id: "frost_shatter",
    name: "Shatter",
    desc: "+10% damage vs chilled foes per rank.",
    rankDescs: ["+10% vs chill.", "+20% vs chill.", "+30% vs chill."],
    maxRank: 3,
    row: 0,
    col: 2,
    requiresPoints: 0,
    scalePerRank: true,
    effect: { kind: "passive", hook: "vs_chilled", power: 10 },
  },
  {
    id: "frost_permafrost",
    name: "Permafrost",
    desc: "Frostbolt chill lasts +1 turn per rank.",
    rankDescs: ["Chill +1 turn.", "Chill +2 turns.", "Chill +3 turns."],
    maxRank: 3,
    row: 1,
    col: 1,
    requires: "frost_shatter",
    requiresPoints: 3,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "frostbolt", statusAmp: { kind: "chill", turnsDelta: 1 } } },
  },
  {
    id: "frost_brain_freeze",
    name: "Brain Freeze",
    desc: "Frost Nova CD −1 per rank (min 0).",
    rankDescs: ["Nova CD −1.", "Nova CD −2.", "Nova CD −3."],
    maxRank: 3,
    row: 1,
    col: 3,
    requires: "frost_shatter",
    requiresPoints: 3,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "nova", cooldownDelta: -1 } },
  },
  {
    id: "frost_ice_floes",
    name: "Ice Floes",
    desc: "Chill potency +0.1 per rank.",
    rankDescs: ["Chill +0.1.", "Chill +0.2.", "Chill +0.3."],
    maxRank: 3,
    row: 2,
    col: 0,
    requires: "frost_permafrost",
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "passive", hook: "dot_amp_chill", power: 1 },
  },
  {
    id: "frost_thermal_void",
    name: "Thermal Void",
    desc: "Fireball +15% vs chilled per rank.",
    rankDescs: ["Fireball +15% vs chill.", "+30% vs chill.", "+45% vs chill."],
    maxRank: 3,
    row: 2,
    col: 2,
    requires: ["frost_permafrost", "frost_brain_freeze"],
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "fireball", bonusVsChillDelta: 0.15 } },
  },
  {
    id: "frost_concentration",
    name: "Cold Snap",
    desc: "+2 MAG per rank.",
    rankDescs: ["+2 MAG.", "+4 MAG.", "+6 MAG."],
    maxRank: 3,
    row: 2,
    col: 4,
    requires: "frost_brain_freeze",
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "stat", mag: 2 },
  },
  {
    id: "frost_glacial_spike",
    name: "Glacial Spike",
    desc: "Frostbolt +8% damage per rank.",
    rankDescs: ["Frostbolt +8%.", "Frostbolt +16%.", "Frostbolt +24%."],
    maxRank: 3,
    row: 3,
    col: 1,
    requires: "frost_ice_floes",
    requiresPoints: 15,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "frostbolt", multDelta: 0.08 } },
  },
  {
    id: "frost_winters_chill",
    name: "Winter's Chill",
    desc: "Crits apply chill (potency per rank).",
    rankDescs: ["Crit chill 2/t.", "Crit chill 3/t.", "Crit chill 4/t."],
    maxRank: 3,
    row: 3,
    col: 3,
    requires: "frost_thermal_void",
    requiresPoints: 15,
    scalePerRank: true,
    effect: { kind: "passive", hook: "crit_dot_chill", power: 2 },
  },
  {
    id: "frost_splitting_ice",
    name: "Splitting Ice",
    desc: "+3% crit per rank.",
    rankDescs: ["+3% crit.", "+6% crit.", "+9% crit."],
    maxRank: 3,
    row: 4,
    col: 0,
    requires: "frost_glacial_spike",
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "passive", hook: "crit_bonus", power: 3 },
  },
  {
    id: "frost_comet_storm",
    name: "Comet Storm",
    desc: "Frostbolt +10% and chill +0.05 per rank.",
    rankDescs: ["Frostbolt +10%.", "Frostbolt +20%.", "Frostbolt +30%."],
    maxRank: 3,
    row: 4,
    col: 2,
    requires: ["frost_glacial_spike", "frost_winters_chill"],
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "frostbolt", multDelta: 0.1, statusAmp: { kind: "chill", powerDelta: 0.05 } } },
  },
  {
    id: "frost_ice_lance",
    name: "Ice Lance",
    desc: "+8% vs chilled per rank.",
    rankDescs: ["+8% vs chill.", "+16% vs chill.", "+24% vs chill."],
    maxRank: 3,
    row: 4,
    col: 4,
    requires: "frost_concentration",
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "passive", hook: "vs_chilled", power: 8 },
  },
  {
    id: "frost_ray_of_frost",
    name: "Ray of Frost",
    desc: "Frostbolt CD unchanged but +12% per rank.",
    rankDescs: ["Frostbolt +12%.", "Frostbolt +24%.", "Frostbolt +36%."],
    maxRank: 3,
    row: 5,
    col: 1,
    requires: "frost_comet_storm",
    requiresPoints: 30,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "frostbolt", multDelta: 0.12 } },
  },
  {
    id: "frost_freezing_rain",
    name: "Freezing Rain",
    desc: "Fireball applies chill on cast per rank.",
    rankDescs: ["Fireball + chill.", "Stronger chill.", "Heavy chill."],
    maxRank: 3,
    row: 5,
    col: 3,
    requires: "frost_winters_chill",
    requiresPoints: 30,
    scalePerRank: true,
    effect: {
      kind: "ability",
      mod: { abilityId: "fireball", extraStatus: { kind: "chill", turns: 2, power: 1.2 } },
    },
  },
  {
    id: "frost_fingers_of_frost",
    name: "Fingers of Frost",
    desc: "+4% crit per rank.",
    rankDescs: ["+4% crit.", "+8% crit.", "+12% crit."],
    maxRank: 3,
    row: 6,
    col: 0,
    requires: "frost_splitting_ice",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "passive", hook: "crit_bonus", power: 4 },
  },
  {
    id: "frost_cold_front",
    name: "Cold Front",
    desc: "Pass Turn ticks cooldowns once.",
    maxRank: 1,
    row: 6,
    col: 2,
    requires: "frost_ray_of_frost",
    requiresPoints: 38,
    effect: { kind: "passive", hook: "pass_cd_tick", power: 1 },
  },
  {
    id: "frost_snowstorm",
    name: "Snowstorm",
    desc: "Nova chill after stun (+1 turn per rank).",
    rankDescs: ["Post-freeze chill.", "Longer chill.", "Deep chill."],
    maxRank: 3,
    row: 6,
    col: 4,
    requires: "frost_ice_lance",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "nova", extraStatus: { kind: "chill", turns: 2, power: 1.3 } } },
  },
  {
    id: "frost_cap_flurry",
    name: "Flurry",
    desc: "★ Frostbolt: 1.4× MAG, heavy chill.",
    maxRank: 1,
    row: 7,
    col: 0,
    requires: "frost_fingers_of_frost",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "frost_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "frostbolt",
        multDelta: 0.4,
        statusAmp: { kind: "chill", turnsDelta: 1, powerDelta: 0.15 },
        rename: "Flurry",
        descOverride: "Rapid ice. 1.4× MAG, heavy chill (3t).",
      },
    },
  },
  {
    id: "frost_cap_frozen_orb",
    name: "Frozen Orb",
    desc: "★ Fireball: 1.8× MAG, spreads chill.",
    maxRank: 1,
    row: 7,
    col: 2,
    requires: "frost_cold_front",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "frost_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "fireball",
        multDelta: 0.3,
        extraStatus: { kind: "chill", turns: 2, power: 1.3 },
        rename: "Frozen Orb",
        descOverride: "Orb of frost. 1.8× MAG + chill.",
      },
    },
  },
  {
    id: "frost_cap_ice_barrier",
    name: "Ice Barrier",
    desc: "★ Frost Nova: deep freeze 2 turns, CD 2.",
    maxRank: 1,
    row: 7,
    col: 4,
    requires: "frost_snowstorm",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "frost_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "nova",
        cooldownDelta: -1,
        rename: "Ice Barrier",
        descOverride: "Deep freeze. Skip 2 enemy turns. CD 2.",
      },
    },
  },
];
