import type { TalentNode } from "../talents";

/** Outlaw Rogue — WoW: Blade Flurry, Roll the Bones, Adrenaline Rush, Between the Eyes. */
export const OUTLAW_TREE_V2: TalentNode[] = [
  {
    id: "out_restless_blades",
    name: "Restless Blades",
    desc: "Pass Turn ticks all cooldowns.",
    maxRank: 1,
    row: 0,
    col: 2,
    requiresPoints: 0,
    effect: { kind: "passive", hook: "pass_cd_tick", power: 1 },
  },
  {
    id: "out_opportunity",
    name: "Opportunity",
    desc: "+4% crit per rank.",
    rankDescs: ["+4% crit.", "+8% crit.", "+12% crit."],
    maxRank: 3,
    row: 1,
    col: 1,
    requires: "out_restless_blades",
    requiresPoints: 3,
    scalePerRank: true,
    effect: { kind: "passive", hook: "crit_bonus", power: 4 },
  },
  {
    id: "out_dirty_tricks",
    name: "Dirty Tricks",
    desc: "Slash applies Bleed per rank.",
    rankDescs: ["Bleed 2/t.", "Bleed 3/t.", "Bleed 4/t."],
    maxRank: 3,
    row: 1,
    col: 3,
    requires: "out_restless_blades",
    requiresPoints: 3,
    scalePerRank: true,
    effect: {
      kind: "ability",
      mod: { abilityId: "slash", extraStatus: { kind: "bleed", turns: 2, power: 2 } },
    },
  },
  {
    id: "out_alacrity",
    name: "Alacrity",
    desc: "Eviscerate CD −1 per rank.",
    rankDescs: ["Eviscerate CD −1.", "CD −2.", "CD −3."],
    maxRank: 3,
    row: 2,
    col: 0,
    requires: "out_opportunity",
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "eviscerate", cooldownDelta: -1 } },
  },
  {
    id: "out_gunpowder",
    name: "Gunpowder Plot",
    desc: "Burn ticks +1 per rank.",
    rankDescs: ["Burn +1/t.", "+2/t.", "+3/t."],
    maxRank: 3,
    row: 2,
    col: 2,
    requires: ["out_opportunity", "out_dirty_tricks"],
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "passive", hook: "dot_amp_burn", power: 1 },
  },
  {
    id: "out_quick_draw",
    name: "Quick Draw",
    desc: "+2 ATK per rank.",
    rankDescs: ["+2 ATK.", "+4 ATK.", "+6 ATK."],
    maxRank: 3,
    row: 2,
    col: 4,
    requires: "out_dirty_tricks",
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "stat", atk: 2 },
  },
  {
    id: "out_blade_flurry",
    name: "Blade Flurry",
    desc: "Slash +8% per rank.",
    rankDescs: ["Slash +8%.", "+16%.", "+24%."],
    maxRank: 3,
    row: 3,
    col: 1,
    requires: "out_alacrity",
    requiresPoints: 15,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "slash", multDelta: 0.08 } },
  },
  {
    id: "out_adrenaline",
    name: "Adrenaline Rush",
    desc: "Signature buff +0.3× next attack per rank.",
    rankDescs: ["Adrenaline +0.3×.", "+0.6×.", "+0.9×."],
    maxRank: 3,
    row: 3,
    col: 3,
    requires: "out_gunpowder",
    requiresPoints: 15,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "spec_outlaw", buffNextMultDelta: 0.3 } },
  },
  {
    id: "out_killing_spree",
    name: "Killing Spree",
    desc: "Kills empower next hit (+8% per rank).",
    rankDescs: ["Kill frenzy +8%.", "+16%.", "+24%."],
    maxRank: 3,
    row: 4,
    col: 0,
    requires: "out_blade_flurry",
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "passive", hook: "kill_frenzy", power: 8 },
  },
  {
    id: "out_grand_melee",
    name: "Grand Melee",
    desc: "Backstab +10% per rank.",
    rankDescs: ["Backstab +10%.", "+20%.", "+30%."],
    maxRank: 3,
    row: 4,
    col: 2,
    requires: ["out_blade_flurry", "out_adrenaline"],
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "backstab", multDelta: 0.1 } },
  },
  {
    id: "out_take_em_by_surprise",
    name: "Take 'em by Surprise",
    desc: "+10% vs bleeding per rank.",
    rankDescs: ["+10% vs bleed.", "+20%.", "+30%."],
    maxRank: 3,
    row: 4,
    col: 4,
    requires: "out_quick_draw",
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "passive", hook: "vs_bleeding", power: 10 },
  },
  {
    id: "out_loaded_dice",
    name: "Loaded Dice",
    desc: "Eviscerate +10% per rank.",
    rankDescs: ["Eviscerate +10%.", "+20%.", "+30%."],
    maxRank: 3,
    row: 5,
    col: 1,
    requires: "out_killing_spree",
    requiresPoints: 30,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "eviscerate", multDelta: 0.1 } },
  },
  {
    id: "out_fan_the_hammer",
    name: "Fan the Hammer",
    desc: "+5% crit per rank.",
    rankDescs: ["+5% crit.", "+10% crit.", "+15% crit."],
    maxRank: 3,
    row: 5,
    col: 3,
    requires: "out_adrenaline",
    requiresPoints: 30,
    scalePerRank: true,
    effect: { kind: "passive", hook: "crit_bonus", power: 5 },
  },
  {
    id: "out_heavy_hitter",
    name: "Heavy Hitter",
    desc: "Slash +12% per rank.",
    rankDescs: ["Slash +12%.", "+24%.", "+36%."],
    maxRank: 3,
    row: 6,
    col: 0,
    requires: "out_loaded_dice",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "slash", multDelta: 0.12 } },
  },
  {
    id: "out_dispatch",
    name: "Dispatch",
    desc: "Backstab +12% vs bleeding per rank.",
    rankDescs: ["+12% vs bleed.", "+24%.", "+36%."],
    maxRank: 3,
    row: 6,
    col: 2,
    requires: "out_grand_melee",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "backstab", bonusVsBleedMult: 1.12 } },
  },
  {
    id: "out_sleight_of_hand",
    name: "Sleight of Hand",
    desc: "+2% dodge per rank.",
    rankDescs: ["+2% dodge.", "+4% dodge.", "+6% dodge."],
    maxRank: 3,
    row: 6,
    col: 4,
    requires: "out_take_em_by_surprise",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "passive", hook: "dodge_bonus", power: 2 },
  },
  {
    id: "out_cap_pistol_shot",
    name: "Pistol Shot",
    desc: "★ Slash: 1.2× ATK, bonus crit vs bleeding.",
    maxRank: 1,
    row: 7,
    col: 0,
    requires: "out_heavy_hitter",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "out_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "slash",
        multDelta: 0.2,
        bonusCritPct: 25,
        bonusVsBleedMult: 1.5,
        rename: "Pistol Shot",
        descOverride: "Quick draw. 1.2× ATK, +25% crit, bonus vs bleed.",
      },
    },
  },
  {
    id: "out_cap_between_the_eyes",
    name: "Between the Eyes",
    desc: "★ Backstab: 2.8× ATK, +20% crit.",
    maxRank: 1,
    row: 7,
    col: 2,
    requires: "out_dispatch",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "out_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "backstab",
        multDelta: 0.3,
        bonusCritPct: 20,
        rename: "Between the Eyes",
        descOverride: "Precision shot. 2.8× ATK, +20% crit.",
      },
    },
  },
  {
    id: "out_cap_roll_the_bones",
    name: "Roll the Bones",
    desc: "★ Eviscerate: 2.0× ATK, deeper bleed.",
    maxRank: 1,
    row: 7,
    col: 4,
    requires: "out_sleight_of_hand",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "out_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "eviscerate",
        multDelta: 0.2,
        statusAmp: { kind: "bleed", powerDelta: 2, turnsDelta: 1 },
        rename: "Roll the Bones",
        descOverride: "Lucky cut. 2.0× ATK, deeper bleed.",
      },
    },
  },
];
