import type { TalentNode } from "../talents";

/** Protection Warrior — WoW-inspired: Shield Slam, Revenge, Ignore Pain, Last Stand, Avatar. */
export const PROTECTION_TREE_V2: TalentNode[] = [
  {
    id: "prot_tough_as_nails",
    name: "Tough as Nails",
    desc: "+4 Max HP and +1% dodge per rank.",
    rankDescs: ["+4 HP, +1% dodge.", "+8 HP, +2% dodge.", "+12 HP, +3% dodge."],
    maxRank: 3,
    row: 0,
    col: 2,
    requiresPoints: 0,
    scalePerRank: true,
    effect: { kind: "stat", maxHp: 4, dodge: 1 },
  },
  {
    id: "prot_shield_mastery",
    name: "Shield Mastery",
    desc: "Shield Wall blocks +4% more per rank.",
    rankDescs: ["Block +4%.", "Block +8%.", "Block +12%."],
    maxRank: 3,
    row: 1,
    col: 1,
    requires: "prot_tough_as_nails",
    requiresPoints: 3,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "wall", reduceDelta: 0.04 } },
  },
  {
    id: "prot_booming_voice",
    name: "Booming Voice",
    desc: "Cleave applies Chill — stronger per rank.",
    rankDescs: ["Cleave chills.", "Stronger chill.", "Heavy chill (3t)."],
    maxRank: 3,
    row: 1,
    col: 3,
    requires: "prot_tough_as_nails",
    requiresPoints: 3,
    scalePerRank: true,
    effect: {
      kind: "ability",
      mod: { abilityId: "cleave", extraStatus: { kind: "chill", turns: 2, power: 1.2 } },
    },
  },
  {
    id: "prot_devastator",
    name: "Devastator",
    desc: "Strike applies Bleed (3t) — power per rank.",
    rankDescs: ["Bleed 2/t.", "Bleed 3/t.", "Bleed 4/t."],
    maxRank: 3,
    row: 2,
    col: 0,
    requires: "prot_shield_mastery",
    requiresPoints: 8,
    scalePerRank: true,
    effect: {
      kind: "ability",
      mod: { abilityId: "strike", extraStatus: { kind: "bleed", turns: 3, power: 2 } },
    },
  },
  {
    id: "prot_revenge",
    name: "Revenge",
    desc: "Cleave +10% and +8% lifesteal per rank.",
    rankDescs: ["Cleave +10%, +8% leech.", "Cleave +20%, +16% leech.", "Cleave +30%, +24% leech."],
    maxRank: 3,
    row: 2,
    col: 2,
    requires: ["prot_shield_mastery", "prot_booming_voice"],
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "cleave", multDelta: 0.1, lifestealDelta: 0.08 } },
  },
  {
    id: "prot_bastion_of_defense",
    name: "Bastion of Defense",
    desc: "+2% dodge per rank.",
    rankDescs: ["+2% dodge.", "+4% dodge.", "+6% dodge."],
    maxRank: 3,
    row: 2,
    col: 4,
    requires: "prot_booming_voice",
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "passive", hook: "dodge_bonus", power: 2 },
  },
  {
    id: "prot_ignore_pain",
    name: "Ignore Pain",
    desc: "Shield Wall heals +4% Max HP per rank.",
    rankDescs: ["Wall heals +4% HP.", "Wall heals +8% HP.", "Wall heals +12% HP."],
    maxRank: 3,
    row: 3,
    col: 1,
    requires: "prot_devastator",
    requiresPoints: 15,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "wall", healPctOnShield: 0.04 } },
  },
  {
    id: "prot_heavy_repercussions",
    name: "Heavy Repercussions",
    desc: "Strike +8% per rank.",
    rankDescs: ["Strike +8%.", "Strike +16%.", "Strike +24%."],
    maxRank: 3,
    row: 3,
    col: 3,
    requires: "prot_revenge",
    requiresPoints: 15,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "strike", multDelta: 0.08 } },
  },
  {
    id: "prot_demoralizing_shout",
    name: "Demoralizing Shout",
    desc: "+3% dodge per rank.",
    rankDescs: ["+3% dodge.", "+6% dodge.", "+9% dodge."],
    maxRank: 3,
    row: 4,
    col: 0,
    requires: "prot_ignore_pain",
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "passive", hook: "dodge_bonus", power: 3 },
  },
  {
    id: "prot_shield_slam",
    name: "Shield Slam",
    desc: "Strike +12% and pierces guard at max rank.",
    rankDescs: ["Strike +12%.", "Strike +24%.", "Strike +36%, pierces guard."],
    maxRank: 3,
    row: 4,
    col: 2,
    requires: ["prot_ignore_pain", "prot_heavy_repercussions"],
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "strike", multDelta: 0.12 } },
  },
  {
    id: "prot_thunderlord",
    name: "Thunderlord",
    desc: "Cleave chill lasts +1 turn per rank.",
    rankDescs: ["Chill +1t.", "Chill +2t.", "Chill +3t."],
    maxRank: 3,
    row: 4,
    col: 4,
    requires: "prot_bastion_of_defense",
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "cleave", statusAmp: { kind: "chill", turnsDelta: 1 } } },
  },
  {
    id: "prot_last_stand",
    name: "Last Stand",
    desc: "Signature Last Stand blocks +5% and heals +5% per rank.",
    rankDescs: ["Last Stand +5% block/heal.", "+10%.", "+15%."],
    maxRank: 3,
    row: 5,
    col: 1,
    requires: "prot_shield_slam",
    requiresPoints: 30,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "spec_prot", reduceDelta: 0.05, healPctOnShield: 0.05 } },
  },
  {
    id: "prot_punish",
    name: "Punish",
    desc: "+10% damage vs chilled foes per rank.",
    rankDescs: ["+10% vs chilled.", "+20% vs chilled.", "+30% vs chilled."],
    maxRank: 3,
    row: 5,
    col: 3,
    requires: "prot_heavy_repercussions",
    requiresPoints: 30,
    scalePerRank: true,
    effect: { kind: "passive", hook: "vs_chilled", power: 10 },
  },
  {
    id: "prot_indomitable",
    name: "Indomitable",
    desc: "+6 Max HP per rank.",
    rankDescs: ["+6 Max HP.", "+12 Max HP.", "+18 Max HP."],
    maxRank: 3,
    row: 6,
    col: 0,
    requires: "prot_demoralizing_shout",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "stat", maxHp: 6 },
  },
  {
    id: "prot_unnerving_focus",
    name: "Unnerving Focus",
    desc: "Shield Wall CD −1 per rank.",
    rankDescs: ["Wall CD −1.", "Wall CD −2.", "Wall CD −3."],
    maxRank: 3,
    row: 6,
    col: 2,
    requires: "prot_last_stand",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "wall", cooldownDelta: -1 } },
  },
  {
    id: "prot_dragon_charge",
    name: "Dragon Charge",
    desc: "Pass Turn ticks cooldowns.",
    maxRank: 1,
    row: 6,
    col: 4,
    requires: "prot_thunderlord",
    requiresPoints: 38,
    effect: { kind: "passive", hook: "pass_cd_tick", power: 1 },
  },
  {
    id: "prot_cap_shield_slam",
    name: "Shield Slam",
    desc: "★ Strike becomes Shield Slam: 1.5× ATK, pierces guard.",
    maxRank: 1,
    row: 7,
    col: 0,
    requires: "prot_indomitable",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "prot_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "strike",
        multDelta: 0.5,
        ignoreGuard: true,
        rename: "Shield Slam",
        descOverride: "Shield bash. 1.5× ATK, pierces guard.",
      },
    },
  },
  {
    id: "prot_cap_avatar",
    name: "Avatar",
    desc: "★ Shield Wall: 90% block + heal 25% Max HP.",
    maxRank: 1,
    row: 7,
    col: 2,
    requires: "prot_unnerving_focus",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "prot_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "wall",
        reduceDelta: 0.2,
        healPctOnShield: 0.25,
        rename: "Avatar",
        descOverride: "Unbreakable. Block 90% next hit, heal 25% Max HP.",
      },
    },
  },
  {
    id: "prot_cap_revenge",
    name: "Revenge",
    desc: "★ Cleave after blocking: 2.0× ATK, +50% lifesteal.",
    maxRank: 1,
    row: 7,
    col: 4,
    requires: "prot_dragon_charge",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "prot_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "cleave",
        multDelta: 0.4,
        lifestealDelta: 0.5,
        rename: "Revenge",
        descOverride: "Vengeful cleave. 2.0× ATK, heavy lifesteal.",
      },
    },
  },
];
