import type { TalentNode } from "../talents";

/** Restoration Druid — WoW: Germination, Swiftmend, Wild Growth, Flourish, Tranquility. */
export const RESTORATION_TREE_V2: TalentNode[] = [
  {
    id: "resto_germination",
    name: "Germination",
    desc: "HoT heals +1 per tick per rank.",
    rankDescs: ["HoT +1/t.", "HoT +2/t.", "HoT +3/t."],
    maxRank: 3,
    row: 0,
    col: 2,
    requiresPoints: 0,
    scalePerRank: true,
    effect: { kind: "passive", hook: "hot_amp", power: 1 },
  },
  {
    id: "resto_cultivation",
    name: "Cultivation",
    desc: "Rejuvenation +1 turn per rank.",
    rankDescs: ["Rejuv +1 turn.", "+2 turns.", "+3 turns."],
    maxRank: 3,
    row: 1,
    col: 1,
    requires: "resto_germination",
    requiresPoints: 3,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "rejuv", hotTurnsDelta: 1 } },
  },
  {
    id: "resto_nourish",
    name: "Nourish",
    desc: "Wrath heals +3% of damage per rank.",
    rankDescs: ["Wrath +3% leech.", "+6% leech.", "+9% leech."],
    maxRank: 3,
    row: 1,
    col: 3,
    requires: "resto_germination",
    requiresPoints: 3,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "wrath", lifestealDelta: 0.03 } },
  },
  {
    id: "resto_swiftmend",
    name: "Swiftmend",
    desc: "Rejuvenation +1 heal/tick per rank.",
    rankDescs: ["Rejuv +1/t.", "+2/t.", "+3/t."],
    maxRank: 3,
    row: 2,
    col: 0,
    requires: "resto_cultivation",
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "rejuv", hotPowerDelta: 1 } },
  },
  {
    id: "resto_photosynthesis",
    name: "Photosynthesis",
    desc: "+2 MAG per rank.",
    rankDescs: ["+2 MAG.", "+4 MAG.", "+6 MAG."],
    maxRank: 3,
    row: 2,
    col: 2,
    requires: ["resto_cultivation", "resto_nourish"],
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "stat", mag: 2 },
  },
  {
    id: "resto_verdancy",
    name: "Verdancy",
    desc: "Moonfire +8% damage per rank.",
    rankDescs: ["Moonfire +8%.", "+16%.", "+24%."],
    maxRank: 3,
    row: 2,
    col: 4,
    requires: "resto_nourish",
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "moonfire", multDelta: 0.08 } },
  },
  {
    id: "resto_abundance",
    name: "Abundance",
    desc: "Rejuvenation +2 heal/tick per rank.",
    rankDescs: ["Rejuv +2/t.", "+4/t.", "+6/t."],
    maxRank: 3,
    row: 3,
    col: 1,
    requires: "resto_swiftmend",
    requiresPoints: 15,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "rejuv", hotPowerDelta: 2 } },
  },
  {
    id: "resto_soul_of_the_forest",
    name: "Soul of the Forest",
    desc: "Below 40% HP, +7% damage per rank.",
    rankDescs: ["+7% damage.", "+14% damage.", "+21% damage."],
    maxRank: 3,
    row: 3,
    col: 3,
    requires: "resto_photosynthesis",
    requiresPoints: 15,
    scalePerRank: true,
    effect: { kind: "passive", hook: "low_hp_dmg", power: 7 },
  },
  {
    id: "resto_flourish_prep",
    name: "Flourish",
    desc: "Pass Turn ticks cooldowns once.",
    maxRank: 1,
    row: 4,
    col: 0,
    requires: "resto_abundance",
    requiresPoints: 22,
    effect: { kind: "passive", hook: "pass_cd_tick", power: 1 },
  },
  {
    id: "resto_overgrowth",
    name: "Overgrowth",
    desc: "Moonfire burn +1 per rank (nature's wrath).",
    rankDescs: ["Moonfire burn +1.", "+2.", "+3."],
    maxRank: 3,
    row: 4,
    col: 2,
    requires: ["resto_abundance", "resto_soul_of_the_forest"],
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "moonfire", statusAmp: { kind: "burn", powerDelta: 1 } } },
  },
  {
    id: "resto_inner_peace",
    name: "Inner Peace",
    desc: "+3 Max HP per rank.",
    rankDescs: ["+3 Max HP.", "+6 Max HP.", "+9 Max HP."],
    maxRank: 3,
    row: 4,
    col: 4,
    requires: "resto_verdancy",
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "stat", maxHp: 3 },
  },
  {
    id: "resto_wild_growth_prep",
    name: "Wild Growth",
    desc: "Rejuvenation +2 heal/tick per rank.",
    rankDescs: ["Rejuv +2/t.", "+4/t.", "+6/t."],
    maxRank: 3,
    row: 5,
    col: 1,
    requires: "resto_overgrowth",
    requiresPoints: 30,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "rejuv", hotPowerDelta: 2, hotTurnsDelta: 1 } },
  },
  {
    id: "resto_tranquility_prep",
    name: "Tranquility",
    desc: "Wrath +10% and +5% leech per rank.",
    rankDescs: ["Wrath +10%, +5% leech.", "+20%, +10% leech.", "+30%, +15% leech."],
    maxRank: 3,
    row: 5,
    col: 3,
    requires: "resto_soul_of_the_forest",
    requiresPoints: 30,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "wrath", multDelta: 0.1, lifestealDelta: 0.05 } },
  },
  {
    id: "resto_embrace_of_the_dream",
    name: "Embrace of the Dream",
    desc: "HoT heals +1 per tick per rank.",
    rankDescs: ["HoT +1/t.", "+2/t.", "+3/t."],
    maxRank: 3,
    row: 6,
    col: 0,
    requires: "resto_flourish_prep",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "passive", hook: "hot_amp", power: 1 },
  },
  {
    id: "resto_ironbark_prep",
    name: "Ironbark",
    desc: "+2% dodge per rank.",
    rankDescs: ["+2% dodge.", "+4% dodge.", "+6% dodge."],
    maxRank: 3,
    row: 6,
    col: 2,
    requires: "resto_wild_growth_prep",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "passive", hook: "dodge_bonus", power: 2 },
  },
  {
    id: "resto_spring_blossoms",
    name: "Spring Blossoms",
    desc: "Burn ticks +1 per rank.",
    rankDescs: ["Burn +1/t.", "+2/t.", "+3/t."],
    maxRank: 3,
    row: 6,
    col: 4,
    requires: "resto_inner_peace",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "passive", hook: "dot_amp_burn", power: 1 },
  },
  {
    id: "resto_cap_wild_growth",
    name: "Wild Growth",
    desc: "★ Rejuvenation: 8 heal/tick, 6 turns.",
    maxRank: 1,
    row: 7,
    col: 0,
    requires: "resto_embrace_of_the_dream",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "resto_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "rejuv",
        hotPowerDelta: 5,
        hotTurnsDelta: 2,
        rename: "Wild Growth",
        descOverride: "Rampant growth. 8 HP/tick for 6 turns.",
      },
    },
  },
  {
    id: "resto_cap_tranquility",
    name: "Tranquility",
    desc: "★ Wrath: 1.3× MAG, heals 50% dealt.",
    maxRank: 1,
    row: 7,
    col: 2,
    requires: "resto_ironbark_prep",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "resto_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "wrath",
        multDelta: 0.3,
        lifestealDelta: 0.5,
        rename: "Tranquility",
        descOverride: "Tranquil bolt. 1.3× MAG, heal half dealt.",
      },
    },
  },
  {
    id: "resto_cap_ironbark",
    name: "Ironbark",
    desc: "★ Moonfire: 1.2× MAG, toughen yourself.",
    maxRank: 1,
    row: 7,
    col: 4,
    requires: "resto_spring_blossoms",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "resto_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "moonfire",
        multDelta: 0.2,
        rename: "Ironbark",
        descOverride: "Barkskin strike. 1.2× MAG, toughen yourself.",
      },
    },
  },
];
