import type { TalentNode } from "../talents";

/** Shadow Priest — WoW: Shadow Weaving, Void Torrent, Mind Blast, Void Eruption, Insanity. */
export const SHADOW_TREE_V2: TalentNode[] = [
  {
    id: "shadow_weaving",
    name: "Shadow Weaving",
    desc: "Burn ticks +1 damage per rank.",
    rankDescs: ["Burn +1/t.", "Burn +2/t.", "Burn +3/t."],
    maxRank: 3,
    row: 0,
    col: 2,
    requiresPoints: 0,
    scalePerRank: true,
    effect: { kind: "passive", hook: "dot_amp_burn", power: 1 },
  },
  {
    id: "shadow_misery",
    name: "Misery",
    desc: "+8% damage vs burning foes per rank.",
    rankDescs: ["+8% vs burn.", "+16% vs burn.", "+24% vs burn."],
    maxRank: 3,
    row: 1,
    col: 1,
    requires: "shadow_weaving",
    requiresPoints: 3,
    scalePerRank: true,
    effect: { kind: "passive", hook: "vs_burning", power: 8 },
  },
  {
    id: "shadow_dark_enlightenment",
    name: "Dark Enlightenment",
    desc: "+3% crit per rank.",
    rankDescs: ["+3% crit.", "+6% crit.", "+9% crit."],
    maxRank: 3,
    row: 1,
    col: 3,
    requires: "shadow_weaving",
    requiresPoints: 3,
    scalePerRank: true,
    effect: { kind: "passive", hook: "crit_bonus", power: 3 },
  },
  {
    id: "shadow_void_torrent",
    name: "Void Torrent",
    desc: "SW:Pain +12% damage per rank.",
    rankDescs: ["SW:Pain +12%.", "SW:Pain +24%.", "SW:Pain +36%."],
    maxRank: 3,
    row: 2,
    col: 0,
    requires: "shadow_misery",
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "swp", multDelta: 0.12 } },
  },
  {
    id: "shadow_vampiric_touch",
    name: "Vampiric Touch",
    desc: "Smite leeches +5% per rank.",
    rankDescs: ["Smite +5% leech.", "+10% leech.", "+15% leech."],
    maxRank: 3,
    row: 2,
    col: 2,
    requires: ["shadow_misery", "shadow_dark_enlightenment"],
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "smite", lifestealDelta: 0.05 } },
  },
  {
    id: "shadow_touch_of_darkness",
    name: "Touch of Darkness",
    desc: "+2 MAG per rank.",
    rankDescs: ["+2 MAG.", "+4 MAG.", "+6 MAG."],
    maxRank: 3,
    row: 2,
    col: 4,
    requires: "shadow_dark_enlightenment",
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "stat", mag: 2 },
  },
  {
    id: "shadow_insanity",
    name: "Insanity",
    desc: "SW:Pain burn +1 turn per rank.",
    rankDescs: ["SW:Pain burn +1t.", "+2t.", "+3t."],
    maxRank: 3,
    row: 3,
    col: 1,
    requires: "shadow_void_torrent",
    requiresPoints: 15,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "swp", statusAmp: { kind: "burn", turnsDelta: 1 } } },
  },
  {
    id: "shadow_death_and_madness",
    name: "Death and Madness",
    desc: "Kills empower next hit (+10% per rank).",
    rankDescs: ["Kill frenzy +10%.", "+20%.", "+30%."],
    maxRank: 3,
    row: 3,
    col: 3,
    requires: "shadow_vampiric_touch",
    requiresPoints: 15,
    scalePerRank: true,
    effect: { kind: "passive", hook: "kill_frenzy", power: 10 },
  },
  {
    id: "shadow_mind_devourer",
    name: "Mind Devourer",
    desc: "Crits ignite (potency per rank).",
    rankDescs: ["Crit burn 3/t.", "Crit burn 4/t.", "Crit burn 5/t."],
    maxRank: 3,
    row: 4,
    col: 0,
    requires: "shadow_insanity",
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "passive", hook: "crit_dot_burn", power: 3 },
  },
  {
    id: "shadow_voidform",
    name: "Voidform",
    desc: "Smite +10% per rank.",
    rankDescs: ["Smite +10%.", "Smite +20%.", "Smite +30%."],
    maxRank: 3,
    row: 4,
    col: 2,
    requires: ["shadow_insanity", "shadow_death_and_madness"],
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "smite", multDelta: 0.1 } },
  },
  {
    id: "shadow_haunting_shadows",
    name: "Haunting Shadows",
    desc: "SW:Pain burn +1 power per rank.",
    rankDescs: ["SW:Pain burn +1.", "+2.", "+3."],
    maxRank: 3,
    row: 4,
    col: 4,
    requires: "shadow_touch_of_darkness",
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "swp", statusAmp: { kind: "burn", powerDelta: 1 } } },
  },
  {
    id: "shadow_mindgames",
    name: "Mindgames",
    desc: "+4% crit per rank.",
    rankDescs: ["+4% crit.", "+8% crit.", "+12% crit."],
    maxRank: 3,
    row: 5,
    col: 1,
    requires: "shadow_voidform",
    requiresPoints: 30,
    scalePerRank: true,
    effect: { kind: "passive", hook: "crit_bonus", power: 4 },
  },
  {
    id: "shadow_distorted_reality",
    name: "Distorted Reality",
    desc: "Below 40% HP, +7% damage per rank.",
    rankDescs: ["+7% damage.", "+14% damage.", "+21% damage."],
    maxRank: 3,
    row: 5,
    col: 3,
    requires: "shadow_death_and_madness",
    requiresPoints: 30,
    scalePerRank: true,
    effect: { kind: "passive", hook: "low_hp_dmg", power: 7 },
  },
  {
    id: "shadow_mind_blast_prep",
    name: "Mind Blast",
    desc: "Smite +15% per rank.",
    rankDescs: ["Smite +15%.", "Smite +30%.", "Smite +45%."],
    maxRank: 3,
    row: 6,
    col: 0,
    requires: "shadow_mind_devourer",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "smite", multDelta: 0.15 } },
  },
  {
    id: "shadow_void_eruption_prep",
    name: "Mind Sear",
    desc: "Unlock Mind Sear — shadow beam hits ALL foes.",
    maxRank: 1,
    row: 6,
    col: 2,
    requires: "shadow_mindgames",
    requiresPoints: 38,
    effect: { kind: "grant_ability", abilityId: "mind_sear" },
  },
  {
    id: "shadow_silent_hymn",
    name: "Silent Hymn",
    desc: "Pass Turn ticks cooldowns once.",
    maxRank: 1,
    row: 6,
    col: 4,
    requires: "shadow_haunting_shadows",
    requiresPoints: 38,
    effect: { kind: "passive", hook: "pass_cd_tick", power: 1 },
  },
  {
    id: "shadow_cap_mind_blast",
    name: "Mind Blast",
    desc: "★ Smite: 1.8× MAG shadow blast.",
    maxRank: 1,
    row: 7,
    col: 0,
    requires: "shadow_mind_blast_prep",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "shadow_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "smite",
        multDelta: 0.8,
        rename: "Mind Blast",
        descOverride: "Psychic blast. 1.8× MAG shadow damage.",
      },
    },
  },
  {
    id: "shadow_cap_void_eruption",
    name: "Void Eruption",
    desc: "★ SW:Pain: 1.8× MAG, devastating burn.",
    maxRank: 1,
    row: 7,
    col: 2,
    requires: "shadow_void_eruption_prep",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "shadow_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "swp",
        multDelta: 0.6,
        statusAmp: { kind: "burn", powerDelta: 4 },
        rename: "Void Eruption",
        descOverride: "Void burst. 1.8× MAG, devastating burn.",
      },
    },
  },
  {
    id: "shadow_cap_shadow_crash",
    name: "Shadow Crash",
    desc: "★ Smite: 1.6× MAG, brutal shadow burn.",
    maxRank: 1,
    row: 7,
    col: 4,
    requires: "shadow_silent_hymn",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "shadow_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "smite",
        multDelta: 0.6,
        extraStatus: { kind: "burn", turns: 5, power: 5 },
        rename: "Shadow Crash",
        descOverride: "Shadow crash. 1.6× MAG + brutal burn.",
      },
    },
  },
];
