import type { TalentNode } from "../talents";

/** Subtlety Rogue — WoW: Find Weakness, Shadow Dance, Shadowstrike, Black Powder. */
export const SUBTLETY_TREE_V2: TalentNode[] = [
  {
    id: "sub_find_weakness",
    name: "Find Weakness",
    desc: "+10% damage vs chilled foes per rank.",
    rankDescs: ["+10% vs chilled.", "+20%.", "+30%."],
    maxRank: 3,
    row: 0,
    col: 2,
    requiresPoints: 0,
    scalePerRank: true,
    effect: { kind: "passive", hook: "vs_chilled", power: 10 },
  },
  {
    id: "sub_shadow_focus",
    name: "Shadow Focus",
    desc: "Backstab CD −1 per rank.",
    rankDescs: ["Backstab CD −1.", "CD −2.", "CD −3."],
    maxRank: 3,
    row: 1,
    col: 1,
    requires: "sub_find_weakness",
    requiresPoints: 3,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "backstab", cooldownDelta: -1 } },
  },
  {
    id: "sub_premeditation",
    name: "Premeditation",
    desc: "+3% crit per rank.",
    rankDescs: ["+3% crit.", "+6% crit.", "+9% crit."],
    maxRank: 3,
    row: 1,
    col: 3,
    requires: "sub_find_weakness",
    requiresPoints: 3,
    scalePerRank: true,
    effect: { kind: "passive", hook: "crit_bonus", power: 3 },
  },
  {
    id: "sub_nightblade",
    name: "Nightblade",
    desc: "Slash applies Chill per rank.",
    rankDescs: ["Chill 2t.", "Chill 3t.", "Chill 4t."],
    maxRank: 3,
    row: 2,
    col: 0,
    requires: "sub_shadow_focus",
    requiresPoints: 8,
    scalePerRank: true,
    effect: {
      kind: "ability",
      mod: { abilityId: "slash", extraStatus: { kind: "chill", turns: 2, power: 1.25 } },
    },
  },
  {
    id: "sub_shadow_dance",
    name: "Shadow Dance",
    desc: "Chill potency +0.05 per rank (foes take more dmg).",
    rankDescs: ["Chill +5% dmg.", "+10%.", "+15%."],
    maxRank: 3,
    row: 2,
    col: 2,
    requires: ["sub_shadow_focus", "sub_premeditation"],
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "passive", hook: "dot_amp_chill", power: 1 },
  },
  {
    id: "sub_cloakwork",
    name: "Cloakwork",
    desc: "+2% dodge per rank.",
    rankDescs: ["+2% dodge.", "+4% dodge.", "+6% dodge."],
    maxRank: 3,
    row: 2,
    col: 4,
    requires: "sub_premeditation",
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "passive", hook: "dodge_bonus", power: 2 },
  },
  {
    id: "sub_eviscerate_shadows",
    name: "Eviscerate from Shadows",
    desc: "Eviscerate +10% per rank.",
    rankDescs: ["Eviscerate +10%.", "+20%.", "+30%."],
    maxRank: 3,
    row: 3,
    col: 1,
    requires: "sub_nightblade",
    requiresPoints: 15,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "eviscerate", multDelta: 0.1 } },
  },
  {
    id: "sub_shadowstrike_mastery",
    name: "Shadowstrike",
    desc: "Signature Shadowstrike +10% per rank.",
    rankDescs: ["Shadowstrike +10%.", "+20%.", "+30%."],
    maxRank: 3,
    row: 3,
    col: 3,
    requires: "sub_shadow_dance",
    requiresPoints: 15,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "spec_sub", multDelta: 0.1 } },
  },
  {
    id: "sub_gloomblade",
    name: "Gloomblade",
    desc: "Slash +10% per rank.",
    rankDescs: ["Slash +10%.", "+20%.", "+30%."],
    maxRank: 3,
    row: 4,
    col: 0,
    requires: "sub_eviscerate_shadows",
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "slash", multDelta: 0.1 } },
  },
  {
    id: "sub_dark_shadow",
    name: "Dark Shadow",
    desc: "Backstab +10% per rank.",
    rankDescs: ["Backstab +10%.", "+20%.", "+30%."],
    maxRank: 3,
    row: 4,
    col: 2,
    requires: ["sub_eviscerate_shadows", "sub_shadowstrike_mastery"],
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "backstab", multDelta: 0.1 } },
  },
  {
    id: "sub_shuriken_tornado",
    name: "Shuriken Tornado",
    desc: "+12% vs chilled per rank.",
    rankDescs: ["+12% vs chilled.", "+24%.", "+36%."],
    maxRank: 3,
    row: 4,
    col: 4,
    requires: "sub_cloakwork",
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "passive", hook: "vs_chilled", power: 12 },
  },
  {
    id: "sub_secret_technique",
    name: "Secret Technique",
    desc: "Eviscerate +12% vs chilled per rank.",
    rankDescs: ["+12% vs chilled on Evis.", "+24%.", "+36%."],
    maxRank: 3,
    row: 5,
    col: 1,
    requires: "sub_gloomblade",
    requiresPoints: 30,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "eviscerate", bonusVsChillDelta: 0.12 } },
  },
  {
    id: "sub_planned_execution",
    name: "Planned Execution",
    desc: "+4% crit per rank.",
    rankDescs: ["+4% crit.", "+8% crit.", "+12% crit."],
    maxRank: 3,
    row: 5,
    col: 3,
    requires: "sub_dark_shadow",
    requiresPoints: 30,
    scalePerRank: true,
    effect: { kind: "passive", hook: "crit_bonus", power: 4 },
  },
  {
    id: "sub_weaponmaster",
    name: "Weaponmaster",
    desc: "+2 ATK per rank.",
    rankDescs: ["+2 ATK.", "+4 ATK.", "+6 ATK."],
    maxRank: 3,
    row: 6,
    col: 0,
    requires: "sub_secret_technique",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "stat", atk: 2 },
  },
  {
    id: "sub_finality",
    name: "Finality",
    desc: "Backstab +12% vs chilled per rank.",
    rankDescs: ["+12% vs chilled.", "+24%.", "+36%."],
    maxRank: 3,
    row: 6,
    col: 2,
    requires: "sub_planned_execution",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "backstab", bonusVsChillDelta: 0.12 } },
  },
  {
    id: "sub_shade",
    name: "Shade",
    desc: "Pass Turn ticks cooldowns.",
    maxRank: 1,
    row: 6,
    col: 4,
    requires: "sub_shuriken_tornado",
    requiresPoints: 38,
    effect: { kind: "passive", hook: "pass_cd_tick", power: 1 },
  },
  {
    id: "sub_cap_shadowstrike",
    name: "Shadowstrike",
    desc: "★ Backstab: 2.8× ATK from the shadows.",
    maxRank: 1,
    row: 7,
    col: 0,
    requires: "sub_weaponmaster",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "sub_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "backstab",
        multDelta: 0.3,
        rename: "Shadowstrike",
        descOverride: "Ambush from shadow. 2.8× ATK.",
      },
    },
  },
  {
    id: "sub_cap_black_powder",
    name: "Black Powder",
    desc: "★ Eviscerate: 2.4× ATK + burn.",
    maxRank: 1,
    row: 7,
    col: 2,
    requires: "sub_finality",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "sub_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "eviscerate",
        multDelta: 0.6,
        extraStatus: { kind: "burn", turns: 3, power: 5 },
        rename: "Black Powder",
        descOverride: "Shadow bomb. 2.4× ATK + burn.",
      },
    },
  },
  {
    id: "sub_cap_symbols",
    name: "Symbols of Death",
    desc: "★ Slash: 1.4× ATK, applies chill.",
    maxRank: 1,
    row: 7,
    col: 4,
    requires: "sub_shade",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "sub_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "slash",
        multDelta: 0.4,
        extraStatus: { kind: "chill", turns: 2, power: 1.35 },
        rename: "Symbols of Death",
        descOverride: "Rune-carved cut. 1.4× ATK + chill.",
      },
    },
  },
];
