import type { TalentNode } from "../talents";

/** Unholy DK — WoW: Festering Wound, Epidemic, Army of the Dead, plague damage. */
export const UNHOLY_TREE_V2: TalentNode[] = [
  {
    id: "unholy_festering_wounds",
    name: "Festering Wounds",
    desc: "Bleed ticks +1 per rank.",
    rankDescs: ["Bleed +1/t.", "+2/t.", "+3/t."],
    maxRank: 3, row: 0, col: 2, requiresPoints: 0, scalePerRank: true,
    effect: { kind: "passive", hook: "dot_amp_bleed", power: 1 },
  },
  {
    id: "unholy_unholy_blight",
    name: "Unholy Blight",
    desc: "+10% vs bleeding per rank.",
    rankDescs: ["+10% vs bleed.", "+20%.", "+30%."],
    maxRank: 3, row: 1, col: 1, requires: "unholy_festering_wounds", requiresPoints: 3, scalePerRank: true,
    effect: { kind: "passive", hook: "vs_bleeding", power: 10 },
  },
  {
    id: "unholy_all_will_serve",
    name: "All Will Serve",
    desc: "Death Strike +10% per rank.",
    rankDescs: ["Death Strike +10%.", "+20%.", "+30%."],
    maxRank: 3, row: 1, col: 3, requires: "unholy_festering_wounds", requiresPoints: 3, scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "deathstrike", multDelta: 0.1 } },
  },
  {
    id: "unholy_defile",
    name: "Death and Decay",
    desc: "Unlock Death and Decay — unholy zone hits ALL foes.",
    maxRank: 1, row: 2, col: 0, requires: "unholy_unholy_blight", requiresPoints: 8,
    effect: { kind: "grant_ability", abilityId: "death_and_decay" },
  },
  {
    id: "unholy_epidemic",
    name: "Epidemic",
    desc: "Burn ticks +1 per rank.",
    rankDescs: ["Burn +1/t.", "+2/t.", "+3/t."],
    maxRank: 3, row: 2, col: 2, requires: ["unholy_unholy_blight", "unholy_all_will_serve"], requiresPoints: 8, scalePerRank: true,
    effect: { kind: "passive", hook: "dot_amp_burn", power: 1 },
  },
  {
    id: "unholy_rotten_touch",
    name: "Rotten Touch",
    desc: "+10% vs burning per rank.",
    rankDescs: ["+10% vs burn.", "+20%.", "+30%."],
    maxRank: 3, row: 2, col: 4, requires: "unholy_all_will_serve", requiresPoints: 8, scalePerRank: true,
    effect: { kind: "passive", hook: "vs_burning", power: 10 },
  },
  {
    id: "unholy_festering_strike_mastery",
    name: "Festering Strike",
    desc: "Signature Festering Strike +10% per rank.",
    rankDescs: ["Festering +10%.", "+20%.", "+36%."],
    maxRank: 3, row: 3, col: 1, requires: "unholy_defile", requiresPoints: 15, scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "spec_unholy", multDelta: 0.1, statusAmp: { kind: "bleed", powerDelta: 1 } } },
  },
  {
    id: "unholy_dark_transformation",
    name: "Dark Transformation",
    desc: "Frost Strike applies bleed per rank.",
    rankDescs: ["FS bleed 3/t.", "4/t.", "5/t."],
    maxRank: 3, row: 3, col: 3, requires: "unholy_epidemic", requiresPoints: 15, scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "froststrike", extraStatus: { kind: "bleed", turns: 3, power: 3 } } },
  },
  {
    id: "unholy_soul_reaper",
    name: "Soul Reaper",
    desc: "Kills empower next hit (+8% per rank).",
    rankDescs: ["Kill frenzy +8%.", "+16%.", "+24%."],
    maxRank: 3, row: 4, col: 0, requires: "unholy_festering_strike_mastery", requiresPoints: 22, scalePerRank: true,
    effect: { kind: "passive", hook: "kill_frenzy", power: 8 },
  },
  {
    id: "unholy_plaguebringer",
    name: "Plaguebringer",
    desc: "Blood Boil +10% per rank.",
    rankDescs: ["Blood Boil +10%.", "+20%.", "+30%."],
    maxRank: 3, row: 4, col: 2, requires: ["unholy_festering_strike_mastery", "unholy_dark_transformation"], requiresPoints: 22, scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "bloodboil", multDelta: 0.1 } },
  },
  {
    id: "unholy_superstrain",
    name: "Superstrain",
    desc: "Bleed + burn synergy: +8% vs bleeding per rank.",
    rankDescs: ["+8% vs bleed.", "+16%.", "+24%."],
    maxRank: 3, row: 4, col: 4, requires: "unholy_rotten_touch", requiresPoints: 22, scalePerRank: true,
    effect: { kind: "passive", hook: "vs_bleeding", power: 8 },
  },
  {
    id: "unholy_unholy_pact",
    name: "Unholy Pact",
    desc: "Death Strike leech +5% per rank.",
    rankDescs: ["+5% leech.", "+10%.", "+15%."],
    maxRank: 3, row: 5, col: 1, requires: "unholy_soul_reaper", requiresPoints: 30, scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "deathstrike", lifestealDelta: 0.05 } },
  },
  {
    id: "unholy_morbidity",
    name: "Morbidity",
    desc: "+12% vs burning per rank.",
    rankDescs: ["+12% vs burn.", "+24%.", "+36%."],
    maxRank: 3, row: 5, col: 3, requires: "unholy_plaguebringer", requiresPoints: 30, scalePerRank: true,
    effect: { kind: "passive", hook: "vs_burning", power: 12 },
  },
  {
    id: "unholy_gift_of_the_sanlayn",
    name: "Gift of the San'layn",
    desc: "+2 ATK per rank.",
    rankDescs: ["+2 ATK.", "+4 ATK.", "+6 ATK."],
    maxRank: 3, row: 6, col: 0, requires: "unholy_unholy_pact", requiresPoints: 38, scalePerRank: true,
    effect: { kind: "stat", atk: 2 },
  },
  {
    id: "unholy_ghoulish_frenzy",
    name: "Ghoulish Frenzy",
    desc: "Pass Turn ticks cooldowns.",
    maxRank: 1, row: 6, col: 4, requires: "unholy_superstrain", requiresPoints: 38,
    effect: { kind: "passive", hook: "pass_cd_tick", power: 1 },
  },
  {
    id: "unholy_cap_festering",
    name: "Festering Strike",
    desc: "★ Death Strike: 1.5× ATK, festering bleed.",
    maxRank: 1, row: 7, col: 0, requires: "unholy_gift_of_the_sanlayn", requiresPoints: 45,
    capstone: true, choiceGroup: "unholy_capstone",
    effect: { kind: "ability", mod: { abilityId: "deathstrike", multDelta: 0.2, statusAmp: { kind: "bleed", powerDelta: 3, turnsDelta: 2 }, rename: "Festering Strike", descOverride: "Festering blade. 1.5× ATK, plague bleed." } },
  },
  {
    id: "unholy_cap_army",
    name: "Army of the Dead",
    desc: "★ Blood Boil: 2.0× ATK, plague burn.",
    maxRank: 1, row: 7, col: 2, requires: "unholy_morbidity", requiresPoints: 45,
    capstone: true, choiceGroup: "unholy_capstone",
    effect: { kind: "ability", mod: { abilityId: "bloodboil", multDelta: 0.3, statusAmp: { kind: "burn", powerDelta: 4 }, rename: "Army of the Dead", descOverride: "Legion boil. 2.0× ATK, plague fire." } },
  },
  {
    id: "unholy_cap_gargoyle",
    name: "Summon Gargoyle",
    desc: "★ Frost Strike: 1.5× ATK, pierces guard.",
    maxRank: 1, row: 7, col: 4, requires: "unholy_ghoulish_frenzy", requiresPoints: 45,
    capstone: true, choiceGroup: "unholy_capstone",
    effect: { kind: "ability", mod: { abilityId: "froststrike", multDelta: 0.5, ignoreGuard: true, rename: "Summon Gargoyle", descOverride: "Gargoyle strike. 1.5× ATK, pierces guard." } },
  },
];
