import type { TalentNode } from "../talents";

/** Vengeance Demon Hunter — WoW: Soul Rending, Fracture, Spirit Bomb, Fel Devastation, self-heal tank. */
export const VENGEANCE_TREE_V2: TalentNode[] = [
  {
    id: "veng_soul_rending",
    name: "Soul Rending",
    desc: "All attacks leech +4% life per rank.",
    rankDescs: ["+4% lifesteal.", "+8% lifesteal.", "+12% lifesteal."],
    maxRank: 3,
    row: 0,
    col: 2,
    requiresPoints: 0,
    scalePerRank: true,
    effect: { kind: "passive", hook: "lifesteal_boost", power: 4 },
  },
  {
    id: "veng_fracture",
    name: "Fracture",
    desc: "Chaos Strike +7% damage per rank.",
    rankDescs: ["Chaos Strike +7%.", "Chaos Strike +14%.", "Chaos Strike +21%."],
    maxRank: 3,
    row: 1,
    col: 1,
    requires: "veng_soul_rending",
    requiresPoints: 3,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "chaosstrike", multDelta: 0.07 } },
  },
  {
    id: "veng_feed_the_demon",
    name: "Feed the Demon",
    desc: "+3 Max HP and +1% dodge per rank.",
    rankDescs: ["+3 HP, +1% dodge.", "+6 HP, +2% dodge.", "+9 HP, +3% dodge."],
    maxRank: 3,
    row: 1,
    col: 3,
    requires: "veng_soul_rending",
    requiresPoints: 3,
    scalePerRank: true,
    effect: { kind: "stat", maxHp: 3, dodge: 1 },
  },
  {
    id: "veng_spirit_bomb",
    name: "Spirit Bomb",
    desc: "Eye Beam leeches +10% per rank.",
    rankDescs: ["Eye Beam +10% leech.", "+20% leech.", "+30% leech."],
    maxRank: 3,
    row: 2,
    col: 0,
    requires: "veng_fracture",
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "eyebeam", lifestealDelta: 0.1 } },
  },
  {
    id: "veng_burning_alive",
    name: "Burning Alive",
    desc: "Burn ticks +1 damage per rank.",
    rankDescs: ["Burn +1/t.", "Burn +2/t.", "Burn +3/t."],
    maxRank: 3,
    row: 2,
    col: 2,
    requires: ["veng_fracture", "veng_feed_the_demon"],
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "passive", hook: "dot_amp_burn", power: 1 },
  },
  {
    id: "veng_fiery_brand",
    name: "Fiery Brand",
    desc: "+10% damage vs burning foes per rank.",
    rankDescs: ["+10% vs burn.", "+20% vs burn.", "+30% vs burn."],
    maxRank: 3,
    row: 2,
    col: 4,
    requires: "veng_feed_the_demon",
    requiresPoints: 8,
    scalePerRank: true,
    effect: { kind: "passive", hook: "vs_burning", power: 10 },
  },
  {
    id: "veng_soul_carver",
    name: "Soul Carver",
    desc: "Fel Rush +10% damage per rank.",
    rankDescs: ["Fel Rush +10%.", "Fel Rush +20%.", "Fel Rush +30%."],
    maxRank: 3,
    row: 3,
    col: 1,
    requires: "veng_spirit_bomb",
    requiresPoints: 15,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "felrush", multDelta: 0.1 } },
  },
  {
    id: "veng_painbringer",
    name: "Painbringer",
    desc: "Below 40% HP, deal +7% damage per rank.",
    rankDescs: ["+7% damage.", "+14% damage.", "+21% damage."],
    maxRank: 3,
    row: 3,
    col: 3,
    requires: "veng_burning_alive",
    requiresPoints: 15,
    scalePerRank: true,
    effect: { kind: "passive", hook: "low_hp_dmg", power: 7 },
  },
  {
    id: "veng_sigil_of_flame",
    name: "Sigil of Flame",
    desc: "Fel Rush burn +1 power per rank.",
    rankDescs: ["Fel Rush burn +1.", "Fel Rush burn +2.", "Fel Rush burn +3."],
    maxRank: 3,
    row: 4,
    col: 0,
    requires: "veng_soul_carver",
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "felrush", statusAmp: { kind: "burn", powerDelta: 1 } } },
  },
  {
    id: "veng_soul_cleave_mastery",
    name: "Soul Cleave",
    desc: "Signature Soul Cleave +10% and +5% leech per rank.",
    rankDescs: ["Soul Cleave +10%, +5% leech.", "+20%, +10% leech.", "+30%, +15% leech."],
    maxRank: 3,
    row: 4,
    col: 2,
    requires: ["veng_soul_carver", "veng_painbringer"],
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "spec_veng", multDelta: 0.1, lifestealDelta: 0.05 } },
  },
  {
    id: "veng_darkglare_boon",
    name: "Darkglare Boon",
    desc: "+5 Max HP per rank.",
    rankDescs: ["+5 Max HP.", "+10 Max HP.", "+15 Max HP."],
    maxRank: 3,
    row: 4,
    col: 4,
    requires: "veng_fiery_brand",
    requiresPoints: 22,
    scalePerRank: true,
    effect: { kind: "stat", maxHp: 5 },
  },
  {
    id: "veng_void_reaver",
    name: "Void Reaver",
    desc: "Chaos Strike +10% and +8% leech per rank.",
    rankDescs: ["Chaos Strike +10%, +8% leech.", "+20%, +16% leech.", "+30%, +24% leech."],
    maxRank: 3,
    row: 5,
    col: 1,
    requires: "veng_soul_cleave_mastery",
    requiresPoints: 30,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "chaosstrike", multDelta: 0.1, lifestealDelta: 0.08 } },
  },
  {
    id: "veng_fel_devastation_prep",
    name: "Fel Devastation",
    desc: "Eye Beam +12% damage per rank.",
    rankDescs: ["Eye Beam +12%.", "Eye Beam +24%.", "Eye Beam +36%."],
    maxRank: 3,
    row: 5,
    col: 3,
    requires: "veng_painbringer",
    requiresPoints: 30,
    scalePerRank: true,
    effect: { kind: "ability", mod: { abilityId: "eyebeam", multDelta: 0.12, lifestealDelta: 0.05 } },
  },
  {
    id: "veng_demon_spikes_prep",
    name: "Demon Spikes",
    desc: "+2% dodge per rank.",
    rankDescs: ["+2% dodge.", "+4% dodge.", "+6% dodge."],
    maxRank: 3,
    row: 6,
    col: 0,
    requires: "veng_sigil_of_flame",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "passive", hook: "dodge_bonus", power: 2 },
  },
  {
    id: "veng_last_resort",
    name: "Last Resort",
    desc: "Below 40% HP, +5% dodge per rank.",
    rankDescs: ["+5% dodge.", "+10% dodge.", "+15% dodge."],
    maxRank: 3,
    row: 6,
    col: 2,
    requires: "veng_void_reaver",
    requiresPoints: 38,
    scalePerRank: true,
    effect: { kind: "stat", dodge: 2, maxHp: 3 },
  },
  {
    id: "veng_charred_flesh",
    name: "Charred Flesh",
    desc: "Pass Turn ticks cooldowns once.",
    maxRank: 1,
    row: 6,
    col: 4,
    requires: "veng_darkglare_boon",
    requiresPoints: 38,
    effect: { kind: "passive", hook: "pass_cd_tick", power: 1 },
  },
  {
    id: "veng_cap_soul_cleave",
    name: "Soul Cleave",
    desc: "★ Chaos Strike: 1.4× ATK, 60% lifesteal.",
    maxRank: 1,
    row: 7,
    col: 0,
    requires: "veng_demon_spikes_prep",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "veng_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "chaosstrike",
        multDelta: 0.3,
        lifestealDelta: 0.4,
        rename: "Soul Cleave",
        descOverride: "Soul drink. 1.4× ATK, heal 60% dealt.",
      },
    },
  },
  {
    id: "veng_cap_fel_devastation",
    name: "Fel Devastation",
    desc: "★ Eye Beam: 2.6× MAG, heals 40% dealt.",
    maxRank: 1,
    row: 7,
    col: 2,
    requires: "veng_last_resort",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "veng_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "eyebeam",
        multDelta: 0.4,
        lifestealDelta: 0.4,
        rename: "Fel Devastation",
        descOverride: "Fel beam. 2.6× MAG, heal 40% dealt.",
      },
    },
  },
  {
    id: "veng_cap_demon_spikes",
    name: "Demon Spikes",
    desc: "★ Fel Rush: 1.8× MAG, armored charge.",
    maxRank: 1,
    row: 7,
    col: 4,
    requires: "veng_charred_flesh",
    requiresPoints: 45,
    capstone: true,
    choiceGroup: "veng_capstone",
    effect: {
      kind: "ability",
      mod: {
        abilityId: "felrush",
        multDelta: 0.2,
        rename: "Demon Spikes",
        descOverride: "Spiked rush. 1.8× MAG, armored charge.",
      },
    },
  },
];
